### ISSUE TITLE
Should we enable gitter.im?

### ISSUE THREAD

**Issue by hemberger** [MechanicalSoup/MechanicalSoup#104]
I was thinking about how to communicate with the other developers of this repository, and it seems that something like [gitter.im](http://gitter.im/) would be suitable. I'd be happy to set it up if you'd like -- it would just take a few clicks. If not, please let me know your preferred method of communication (@moy in particular, since you are currently the most active dev).

**Comment by moy** [comment]
I'm more comfortable with asynchronous communication (email, issues, ...), so I have no objection to setting up gitter, but I can't guarantee I'll be active there.

**Comment by hemberger** [comment]
Something like gitter.im is a nice place to leave messages that aren't important enough to be a github issue. You can also set it up so that you're only notified if someone mentions you explicitly. However, it certainly isn't necessary, and it seems like it would be an extra complication for you, which I completely understand! We can keep it in mind for the future, but I'll close this issue for now.
