### ISSUE TITLE
Development workflow and test dependencies

### ISSUE THREAD

**Issue by hemberger** [MechanicalSoup/MechanicalSoup#109]
Somewhat related to Issue #100, the development dependencies listed in `README.md` can easily get out of sync with those used by the tests (and actively tested against by Travis-CI), e.g. see PR #108. Perhaps we should move to the "requirements file" scheme with a `requirements.txt` and `tests/requirements.txt` (or `test_requirements.txt`, which for better or worse is consistent with what Tox uses).

The thing I normally dislike about requirements files is that it makes the manual installation more complicated (you need to include `-r requirements.txt`). However, it seems simple to programmatically read these files in `setup.py`: https://stackoverflow.com/a/29871401.

Assuming this works as advertised, does this seem like a reasonable resolution to the desync problem?

**Comment by moy** [comment]
I was thinking the same. Actually, it's a pity we can't just run something like `python setup.py install-dependencies` or so, but I didn't find a better way than parsing a requirement file as you suggest.

IOW, I'm all for the proposed change.

**Comment by moy** [comment]
PS: I think it would make sense to have both test-dependencies and non-test dependencies in two requirement files. For example, readthedocs needs to install bs4 to generate the doc properly and it accepts a requirement file. For now I've ticked the "Install your project inside a virtualenv using setup.py install" box in the advanced settings, and the installation installs the dependencies as a side-effect, but it would be cleaner to provide the requirement file.

**Comment by hemberger** [comment]
Does anything more need to be done with the requirements files before closing this issue?

**Comment by moy** [comment]
I think it can be closed.
