### ISSUE TITLE
MechanicalSoup logo

### ISSUE THREAD

**Issue by hemberger** [MechanicalSoup/MechanicalSoup#111]
In the [Roadmap](https://github.com/MechanicalSoup/MechanicalSoup#roadmap), some artwork is requested. I asked an artistic friend to try to interpret this request, and this is what they came up with. I would love to use this as our logo (in both the README, as per the roadmap, and perhaps also as our organization icon). Before I make a PR, I just wanted to see if this was what you were going for.

<img src="https://user-images.githubusercontent.com/846186/31482896-0d0d8098-aedf-11e7-8fc8-fc45c6af5e31.png" alt="Drawing" width="240" />

**Comment by moy** [comment]
I like the idea very much. I think the design can be improved by having less details, to be more readable for small versions of the icon (ideally readable for favicon).

**Comment by hemberger** [comment]
Great! The artist is happy to do another iteration of the drawing (with fewer noodles, perhaps bigger gears, ... any other thoughts?). In the meantime, I've added it as our organization profile picture to get a sense of what it currently looks like in some of the applications that use a small version of the icon. Please let me know if this is a problem!

**Comment by hemberger** [comment]
One thing I noticed is that we might want to use a transparent background (since the white background of the image is visible against the slightly off-white background of the [organization page](https://github.com/MechanicalSoup).

**Comment by moy** [comment]
Good.

Perhaps it would help if the noodles had more different colors. As is, it's hard to distinguish noodles, hence to notice they are noodles on the small version. Anyway, it's cool, and if it gets better, it's even cooler.

Once we agree on the design, we can:

- [ ] Commit it to the repo
- [ ] Include it in the README
- [ ] Include it in the docs (readthedocs -> docs/ directory)

**Comment by hemberger** [comment]
Do you want the logo used as-is and then updated when the artist reworks it, or do you want to wait until the logo is "finalized" first?

**Comment by moy** [comment]
I'd rather avoid committing a png file too many times (poor delta-compression => repository size increased forever for little benefit). If you have a (small enough) .svg file to commit, that can be done now.

**Comment by moy** [comment]
Any news from the artist?

**Comment by moy** [comment]
@hemberger : ping?

If we don't get an updated version, perhaps we can decide that this version is the final one.

**Comment by hemberger** [comment]
We do have an updated image (in svg) that addresses your suggestions, but I need to talk to the artist first before I post it here.

**Comment by moy** [comment]
Any news?

If not, I suggest we adopt the current logo as our official one. I started getting used to it :-).

**Comment by hickford** [comment]
Only just seen this... Awesome! I really like it. Perfectly fits how I imagined. *Mechanical soup*! @hemberger Please thank your friend. I want to share this with everyone I know

**Comment by hemberger** [comment]
Glad you like it! The artist was working on an SVG version, but I think they were too unsatisfied with it to share it publicly. So do we want to keep using this informally, or include it somewhere in our docs/repo as well?

**Comment by mkormendy** [comment]
I'm a Graphic Designer by education. Would you guys like me to hack something in PNG format together?

**Comment by mkormendy** [comment]
![artboard 1](https://user-images.githubusercontent.com/1437667/44072913-f4dd31ee-9f56-11e8-945a-83d5f7ef1705.jpg)

**Comment by hemberger** [comment]
Wow @mkormendy, that's pretty amazing! I like it a lot, and it's very generous of you to donate your talents here. :)

I'll talk with @moy next chance I get to see how he'd like to proceed.

**Comment by mkormendy** [comment]
No problem. You guys are generously making something I am trying to use for one of my projects.

**Comment by moy** [comment]
indeed, @mkormendy's proposal is really cool too. To be sure: can you confirm that you did not use any non-free content to make the logo? I don't care deeply whether the tool used to make it is free, but any non-free content would make the logo non-free too.

**Comment by mkormendy** [comment]
I'm looking at using [Zilla Slab](https://fonts.google.com/specimen/Zilla+Slab) as the typeface, along with Open Sans for the subtitle. They both fall under the [Open Font License](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL_web)

**Comment by mkormendy** [comment]
Here's the updated image with the Open Font License fonts.
![screen shot 2018-08-18 at 1 32 15 am](https://user-images.githubusercontent.com/1437667/44296545-a9082200-a286-11e8-8814-62bbd57f7338.png)
