### ISSUE TITLE
Documentation and readthedocs

### ISSUE THREAD

**Issue by moy** [MechanicalSoup/MechanicalSoup#114]
MechanicalSoup is great, but its documentation isn't ...

Among the issues:

* Many pieces of code are just undocumented (not even a docstring)
* We don't have a good tutorial other than "read example.py and do the same" / "read the testsuite"

My guess is that one of the reasons for that is we don't have a good incentive to document (even if we had docstrings, we don't want the documentation to be only available by browsing the source code).

I did two steps in what I think is the right direction:

* A few recent commits in the code to get Sphinx (the standard Python documentation tool) to work, and enable [autodoc](http://www.sphinx-doc.org/en/stable/ext/autodoc.html) to extract docstrings into the manual automatically.

* Play with http://readthedocs.org/. For those who don't know the service, it does to documentation what Travis-CI does for tests: watch the repo, rebuild the doc on new commits. I've set it up at http://mechanicalsoup.readthedocs.io/. For example, the doc extracted from `StatefulBrowser` is here:
http://mechanicalsoup.readthedocs.io/en/latest/mechanicalsoup.html#module-mechanicalsoup.stateful_browser. (edit: I initially created a project with another name but @hickford added me as maintainer to the existing readthedocs project)

Next steps are:

- [x] Advertise for readthedocs from our README.
- [x] Restructure the documentation, so that GitHub becomes the developer's place, and readthedocs / pypi the user-facing sites (i.e. README on GitHub should be just a few teaser paragraphs, as much as possible shared with the Spinx introduction + link to readthedocs, and then the few dev hints we already have)
- [x] Add missing docstrings
- [x] Add a nice beginner's tutorial (and close the long-lasting #6)
- [x] Add an FAQ ("How do I ...") pointing to the API autogenerated doc (skeleton in docs/faq.rst)
- [ ] and of course, include our new logo in the docs ;-) (see #111 in case you missed it)

What do you think?

**Comment by hickford** [comment]
If it helps, I've added you as a maintainer at https://readthedocs.org/projects/mechanicalsoup/

**Comment by moy** [comment]
Perfect, it works now at http://mechanicalsoup.readthedocs.io/ (updated the text above accordingly).

**Comment by moy** [comment]
OK, the logo has its own issue, let's close this one.
