### ISSUE TITLE
Still getting Codecov PR comments

### ISSUE THREAD

**Issue by hemberger** [MechanicalSoup/MechanicalSoup#116]
Even though we've disabled the Codecov PR comments in `.codecov.yml`, we are still getting them. This is not an issue with an invalid YAML file:

```
curl --data-binary @.codecov.yml https://codecov.io/validate
Valid!

{
  "comment": false
}
```

I noticed that this was an issue in the past with Codecov (see https://github.com/codecov/support/issues/162). However, it looks like this might simply be caused by filename confusion (https://github.com/codecov/support/issues/431), where Codecov documents that `.codecov.yml` works, but it actually requires `codecov.yml`.

Perhaps the easiest thing to try is a file rename.

**Comment by moy** [comment]
It seems a rename is the way to go indeed.

**Comment by hemberger** [comment]
Tested with PR #117. No Codecov PR comment was added, so I'm marking this as fixed.
