### ISSUE TITLE
build_sphinx does not rebuild when code changes

### ISSUE THREAD

**Issue by hemberger** [MechanicalSoup/MechanicalSoup#128]
It seems that if no files are modified in `docs/`, then `python setup.py build_sphinx` does not rebuild the documentation unless `docs/_build` is deleted first. This is true even if files in `mechanicalsoup/` _are_ modified.

We should either rebuild the docs on every call (which is presently fast enough to be a reasonable solution) or add `mechanicalsoup/` to the Make dependencies (presumably?). It's not immediately clear to me how to do either of these.

**Comment by moy** [comment]
Modifying the Makefile would have no impact, the Makefile is just here for convenience, as far as I can tell it's not used internally by Sphinx (deleting it doesn't change anything for example). I've just pushed a PR with an alternative approach.
