### ISSUE TITLE
Re-activate warning about unspecified parser or set a default

### ISSUE THREAD

**Issue by moy** [MechanicalSoup/MechanicalSoup#136]
The discussion started a while ago at https://github.com/MechanicalSoup/MechanicalSoup/commit/014b00c9069c997b76d91968bb37ccdd764aa1b3 but never really concluded.

Summary: BeautifulSoup has several ways to choose the HTML parser for the caller of the library (i.e. us):

1) Create a BeautifulSoup object without specifying the parser. Then, BeautifulSoup picks the best available parser and issues a warning ([Beautiful Soup ranks lxml’s parser as being the best, then html5lib’s, then Python’s built-in parser."](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#specifying-the-parser-to-use))
2) Hard-code the parser when creating the object, which silents the the warning.
3) Use `warnings.filterwarnings` to silent the warning, but keep the "pick the best available" behavior of 1).

MechanicalSoup has historically used 1), then 2) and since 014b00c9069c997b76d91968bb37ccdd764aa1b3 it uses 3). I disagree that this is the right thing to do.

The point of MechanicalSoup is to automate things, and in this perspective, having reproducible behavior is far more important that having "best effort" behavior.

For example, I'm developing a tool that has to work around a lot of bugs in the remote server (invalid HTML & stuff), and it is very important that the workarounds I implement on my machine work the same on other people's machine. If my users install a super cool parser that bs4 prefers over the one I have on my machine, they'll get a different behavior, different bugs, they may report bugs that I won't be able to reproduce on my system, ... OTOH, the super cool features they have with their superior parser won't be of any help, because I as a developer did not use them.

And conversely, if I need to install a super cool parser to develop a tool, then I want the tool to error out immediately if the end user doesn't have it. This way, the user will get an explicit error message rather than a broken tool.

One drawback of the current behavior is that it's bad practice to instantiate `Browser` without argument, and we still want to do that in short examples.

My preference would go to option 2), i.e. essentially revert 014b00c9069c997b76d91968bb37ccdd764aa1b3. To avoid having the parser completely hardcoded on our side, we can let `Browser.__init__` take `html_parser="lxml"`, so the caller of MechanicalSoup can easily set the parser as argument to `__init__`, but still get reproducible behavior by default. We need a bit of magic to make sure people currently using `soup_config` still get the parser they specified, but that should be easy.

Thoughts?

**Comment by hemberger** [comment]
I was actually about to submit an issue for this since I noticed the FAQ was no longer relevant.

I agree that reproducibility is very important. What if we did the following:
* Add a default argument: `soup_config={'features': 'lxml'}`
* Remove the parser warning suppression

Then, if someone overrides the default `soup_config`, but fails to specify a parser, then they will get the bs4 parser warning and can consult our FAQ to see how to deal with it.

**Comment by moy** [comment]
Indeed, specifying a default `soup_config` seems the best way to deal with the situation. We'll probably need to add lxml to our requirements.txt.

**Comment by moy** [comment]
OK, it was a bit harder that I thought because we had several places where we relied on the default parser.

One issue is that the new code forces a dependency on `lxml`, but I think it's worth the trouble. It's just a `pip install lxml` away.
