### ISSUE TITLE
Tests randomly hanging on Travis-CI

### ISSUE THREAD

**Issue by hemberger** [MechanicalSoup/MechanicalSoup#146]
Every couple of Travis builds, I see one of the sub-builds hang. It happens frequently enough that I feel like I have to babysit Travis, which is not a good situation to be in. From what I can tell, this occurs under two conditions:
1. httpbin.org is under heavy load (this occurs infrequently, but can occur for extended periods of time)
2. flake8 hangs for some unknown reason (seems arbitrary, and rerunning almost always fixes it)

I really want to understand 2), because for 1) we could simply rely on httpbin.org a bit less if necessary.

**Comment by hemberger** [comment]
I will start logging the stalls I see so that we can try to figure out what is going on.

* Build [#406.5](https://travis-ci.org/MechanicalSoup/MechanicalSoup/jobs/292331319) (pypy) stalled on flake8 test of `tests/test_stateful_browser.py`.

**Comment by moy** [comment]
I'm observing the same thing, but I didn't investigate yet.

For 1., we could maybe guard the whole testsuite with stg like

    if ! curl http://httpbin.org; then sleep $(($RANDOM % 100 + 100)); fi

For 2., are you sure it's flake8? My feeling was that it was occurring after flake8, at the beginning of tests, but again I did not look into the details.

**Comment by hemberger** [comment]
I think a guard like that would be useful, but only for Travis. If I were running tests locally and httpbin was down, I'd rather see the failures than have the tests appear to hang for a while.

The reason I suspect flake8 is because (at least the last couple times I've checked), the hang occurred before the first `.` for a file, which is the flake8 test. We could add `-v` to `addopts` in `setup.cfg` for a little more verbosity.

**Comment by moy** [comment]
> I think a guard like that would be useful, but only for Travis. 

Yes, I was thinking of adding the guard to .travis-ci.yml.

> the hang occurred before the first . for a file

I *think* (but I don't find a way to access the restarted tests logs on Travis, so I don't have an example at hand to check) I saw it after at least some flake8 tests, but not sure it was after all of them. We'll see next time.

> We could add -v to addopts in setup.cfg for a little more verbosity.

Yes, probably the way to go. When we have detailed logs about the failure it'll be easier to debug.

**Comment by hemberger** [comment]
Build [#413.5](https://travis-ci.org/MechanicalSoup/MechanicalSoup/jobs/293349216) (pypy) stalled on flake8 on `form.py`.
![image](https://user-images.githubusercontent.com/846186/32076480-f82f7308-ba54-11e7-9743-fa604522c83d.png)

**Comment by moy** [comment]
Strange indeed, and that's clearly between two flake8 checks. Looks a lot like a Travis-CI issue (the container of the machine freezing for a bad reason). Maybe you can try with `--debug` + stg like `after_failure: cat pytestdebug.log` in `.travis-ci.yml`.

**Comment by hemberger** [comment]
* Build #419.5 (pypy) stalled on the flake8 test of `mechanicalsoup/browser.py`.

**Comment by hemberger** [comment]
* Build [#421.6](https://travis-ci.org/MechanicalSoup/MechanicalSoup/jobs/294797417) (pypy3) stalled on the flake8 test of `tests/setpath.py`.

**Comment by hemberger** [comment]
* Build [#424.5](https://travis-ci.org/MechanicalSoup/MechanicalSoup/jobs/295892357) (pypy) stalled on the flake8 test of `mechanicalsoup/browser.py`.
* Build [#424.6](https://travis-ci.org/MechanicalSoup/MechanicalSoup/jobs/295892358) (pypy3) stalled on the flake8 test of `tests/test_form.py`.

I'm noticing that this is a trend with pypy. Perhaps this is something we can report to Travis?

**Comment by hemberger** [comment]
* Build [#426.6](https://travis-ci.org/MechanicalSoup/MechanicalSoup/jobs/295982015) (pypy3) stalled on the flake8 test of `tests/setpath.py`.

**Comment by hemberger** [comment]
* Build [#429.5](https://travis-ci.org/MechanicalSoup/MechanicalSoup/jobs/296413632) (pypy) stalled on the flake8 test of `mechanicalsoup/form.py`.

**Comment by moy** [comment]
This looks very much like a big with Travis' pypy setup...

With a bit of patience, we could maybe reproduce this in a debug VM (https://docs.travis-ci.com/user/running-build-in-debug-mode/). If we can run ps, pstree, top, strace & friends while the build is hanging, we may get hints about what's going on.

**Comment by hemberger** [comment]
I have e-mailed `support@travis-ci.com` and will relay anything they have to say about the issue.

**Comment by hemberger** [comment]
* Build [#433.5](https://travis-ci.org/MechanicalSoup/MechanicalSoup/jobs/296460879) (pypy) stalled on the flake8 test of `mechanicalsoup/form.py`.

I will continue to monitor this, but don't see the need to report the same issue repeatedly. I'll update here if anything changes.

**Comment by moy** [comment]
* [Job #440.6](https://travis-ci.org/MechanicalSoup/MechanicalSoup/jobs/297649371) (pypy3) stalled on the flake8 test of `mechanicalsoup/form.py`.
* [Job #440.5](https://travis-ci.org/MechanicalSoup/MechanicalSoup/jobs/297649370) (pypy) stalled on the flake8 test of `mechanicalsoup/utils.py`

You're not the only one seeing the trend on pypy ;-).

**Comment by hemberger** [comment]
It's almost worth considering taking PyPy out of the Travis builds so that we don't have to babysit every build.

**Comment by hemberger** [comment]
I used the following Dockerfile to test the speeds with python3 vs. pypy3
```
#FROM python:latest
FROM pypy:latest

RUN git clone https://github.com/MechanicalSoup/MechanicalSoup.git
WORKDIR ./MechanicalSoup
RUN pip install pytest-runner
RUN pip install -r requirements.txt -r tests/requirements.txt

CMD ["pytest"]
```
With `python:latest`, the tests completed on average in 10 seconds. However, with `pypy:latest`, they completed on average in 50 seconds, and it was abundantly clear that it was the flake8 tests that were slow. So there is a very real issue here in the way that flake8 works in pypy. The fact that it actually stalls on Travis seems odd, but I don't think Travis is doing anything wrong.

**Comment by moy** [comment]
Did you check whether running a plain `flake8` or running it through pytest was making any difference?

But note that if Travis's message is correct, the build is killed after 10 minutes without any output on stdout. It's not just slow, it didn't move for 10 minutes.

One possible workaround for us would be to disable flake8 for pypy tests. No idea how to do that with the pytest launcher, but at worse, if we take the flake8 part back to a separate step, then it's easy.
