### ISSUE TITLE
what the difference between this and selenium?

### ISSUE THREAD

**Issue by Kiris-tingna** [MechanicalSoup/MechanicalSoup#153]

**Comment by hemberger** [comment]
MechanicalSoup interacts with HTML elements (allowing you to parse web pages, fill and submit forms, etc.) whereas Selenium simulates a fully-fledged web browser. As a result, the biggest difference between the two is that Selenium can interact with JavaScript. If you don't need JavaScript, then MechancialSoup is a simple, light-weight solution!

**Comment by moy** [comment]
Reopening since I think this deserves a mention in our FAQ (close to the comparison with mechanize).

**Comment by Kiris-tingna** [comment]
thanks @hemberger

**Comment by moy** [comment]
A bit more details:

http://mechanicalsoup.readthedocs.io/en/latest/faq.html#how-does-mechanicalsoup-compare-to-the-alternatives
