### ISSUE TITLE
print_summary

### ISSUE THREAD

**Issue by AndreWin** [MechanicalSoup/MechanicalSoup#154]
Hello!

MechanicalSoup 0.8.0

I read tutorial now https://mechanicalsoup.readthedocs.io/en/latest/tutorial.html
and try this lib in Jupyter Notebook.

```
browser.get_current_form().print_summary()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-cf464b3564b4> in <module>()
----> 1 browser.get_current_form().print_summary()

AttributeError: 'Form' object has no attribute 'print_summary'
```

Best regards,
Andrey.

**Comment by moy** [comment]
Hi,

`print_summary` is a new function, not yet released. Either upgrade (e.g. `pip install git+https://github.com/MechanicalSoup/MechanicalSoup` to get the unreleased version) or don't use `print_summary()` (it's a nice convenience feature, but you can easily do without).

Also, I don't think you need MechanicalSoup to interact with Jupyter Notebook, as it has a REST API (https://github.com/jupyter/jupyter/wiki/Jupyter-Notebook-Server-API).

**Comment by AndreWin** [comment]
@moy, thank you! I will install mechanicalsoup from github.

P.S.: I don't interact with Jupyter Notebook. I work in it. I write my code in it and see results.
