### ISSUE TITLE
Badges for stable version of Read the Docs

### ISSUE THREAD

**Issue by hemberger** [MechanicalSoup/MechanicalSoup#156]
Our badges should give users added confidence in MechanicalSoup, but most are not included in Read the Docs. However, including them as-is would result in the stable build of Read the Docs pointing to the development badges (which can be misleading and confusing).

If we want to include the correct badges in the docs, is there any way we can modify our release structure to do this? This is already accounted for in the PyPI badges (since those correspond to the latest release anyway), but the Build / Coverage / Requirements badges refer to specific branches. Could we make a new branch for each release (perhaps instead of, or in addition to, tagging), and include the latest release branch badges in the docs?

**Comment by moy** [comment]
First, our stable release essentially has no doc, so we should start worrying about this after the next release.

Yes, I like the idea of having a branch dedicated to releases, in which we can do a few adjustments. The history can typically look like:

<pre>
* heads/master  Post-release commit on dev (e.g. prepare the appropriate section in ChangeLog & cie)
| * tag/vx.y.1  Possibly bugfix commits here
| * tag/vx.y.0  Stable release
| * Adust version number, links to badges targets to stable
|/
* last commit before starting release x.y.0
* ...
</pre>

(We just need to be careful that with this setup, merging the maintenance branch to master includes the "Adjust ..." commits in master which we don't want)

**Comment by hemberger** [comment]
Badges show up on the following page:

http://mechanicalsoup.readthedocs.io/en/stable/introduction.html#installation

I think the only reason to modify the badges on our release branches would be if a change on master would affect the stable docs badges. But since these badges come from PyPI, they should always be consistent with the last pip release, right?

If so, then I'd agree that we can close this.

**Comment by moy** [comment]
The badges we have aren't affected by changes on master. This issue was about adding more badges (the ones that are on GitHub and not on Read The Docs. I don't think this would bring much (the other badges are developer-oriented, and we have GitHub for developers). So, I think we can close this.

**Comment by hemberger** [comment]
Hah, yes, you're right. I had forgotten the point of the request, even though it was mine to begin with! I agree completely.
