### ISSUE TITLE
Install using pip fails

### ISSUE THREAD

**Issue by philrandal** [MechanicalSoup/MechanicalSoup#161]
setup.py expects to find requirements.txt in the same directory as itself.

Unfortunately, the .zip file installed via pip has a requires.txt in MechanicalSoup.egg-info, but no requirements.txt anywhere, so setup.py doesn't find it and fails

See http://www.diyaudio.com/forums/pc-based/271811-moode-audio-player-raspberry-pi-post5235363.html

**Comment by moy** [comment]
Thanks, fixed.

You may need a `pip install --no-cache-dir` to force downloading the latest version.
