### ISSUE TITLE
Request Adapters Example

### ISSUE THREAD

**Issue by bleuf1shi** [MechanicalSoup/MechanicalSoup#168]
I'd appreciate an example in the documentation for using Request Adapters in the constructor of a StatefulBrowser. See: https://mechanicalsoup.readthedocs.io/en/stable/mechanicalsoup.html

My specific use case is that I want to increase the retry count and timeout duration for all requests made by the StatefulBrowser.

Thanks

**Comment by hemberger** [comment]
Hello, and thanks for the suggestion!

I think it would be a very good idea to add some documentation about using `requests_adapters`. I've never used them personally, so I'll have to do some testing, but I think the basic scheme is the following:

```python
import mechanicalsoup
from requests.adapters import HTTPAdapter

browser = mechancialsoup.StatefulBrowser(
    requests_adapters={'http://', HTTPAdapter(max_retries=3)}
)

...

# timeout in seconds
browser.submit_selected(timeout=1)
```
If you want more fine control of the retry behavior, pass a `urllib3.util.Retry` to `max_retries` instead of an int.

Does this type of information help, or are you looking for something more detailed?

**Comment by bleuf1shi** [comment]
@hemberger thanks. I've tried the following per your suggestion:
```
resp = browser.open(
        url=report_csv_url,
        timeout=900
    )
```
The endpoint url is one that takes a long time to respond since the server generates a CSV. Performing the requests in Chrome on MacOS take about 5-15min to respond and begin the download. However, when using mechanicalsoup, I'm thrown the following exception:

> ERROR:  ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
>     chunked=chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 2, in raise_from
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
>     httplib_response = conn.getresponse()
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
>     response.begin()
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
>     version, status, reason = self._read_status()
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
>     return self._sock.recv_into(b)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1009, in recv_into
>     return self.read(nbytes, buffer)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 871, in read
>     return self._sslobj.read(len, buffer)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 631, in read
>     v = self._sslobj.read(len, buffer)
> ConnectionResetError: [Errno 54] Connection reset by peer
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
>     timeout=timeout
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
>     raise value.with_traceback(tb)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
>     chunked=chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 2, in raise_from
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
>     httplib_response = conn.getresponse()
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
>     response.begin()
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
>     version, status, reason = self._read_status()
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
>     return self._sock.recv_into(b)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1009, in recv_into
>     return self.read(nbytes, buffer)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 871, in read
>     return self._sslobj.read(len, buffer)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 631, in read
>     v = self._sslobj.read(len, buffer)
> urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mechanicalsoup/stateful_browser.py", line 127, in open
>     resp = self.get(url, *args, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mechanicalsoup/browser.py", line 106, in get
>     response = self.session.get(*args, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
>     return self.request('GET', url, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
>     r = adapter.send(request, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
>     raise ConnectionError(err, request=request)
> requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

The exception is thrown after exactly 5min which led me to believe it's an issue that could be solved by increasing the timeout. 300 seconds is 5min and I'm passing 900 seconds.

Any ideas?

**Comment by bleuf1shi** [comment]
I may have fixed it following the advice from https://stackoverflow.com/a/38854398 
I'll let ya know.

**Comment by hemberger** [comment]
Great, I look forward to hearing if this resolves the issue.

**Comment by moy** [comment]
@bleuf1shi : any news?

**Comment by bleuf1shi** [comment]
@moy , yes. The advice I found ( https://github.com/MechanicalSoup/MechanicalSoup/issues/168#issuecomment-345387976 ) along with extending the connection and read timeouts did resolve the issue.
