### ISSUE TITLE
[How-to]: is there a "download" function?

### ISSUE THREAD

**Issue by aborruso** [MechanicalSoup/MechanicalSoup#170]
Hi,
first of all thank you, this is a great tool!!

I have writter a stupid hello world example (below). At the end I have an URL for which I would like to start a file download.

How to do it?

Thank you

```python
import mechanicalsoup
browser.open("http://albopretorio.comune.palermo.it/albopretorio/jsp/home.jsp?modo=info&info=servizi.jsp&ARECOD=70&SERCOD=-1&sportello=albopretorio")
browser.follow_link("TD=60")
browser.follow_link("TD=2013")
browser.follow_link("row=0")
myPdfURL=browser.follow_link("idx=0")
myPdfURL.url
```

**Comment by hemberger** [comment]
Thanks for your interest in MechanicalSoup!

The return value of `StatefulBrowser::follow_link` is a [requests.Response](http://docs.python-requests.org/en/master/api/#requests.Response) object. If the request is successful, then the data you want is stored in the `Response.content` attribute. So, to download the file amounts to writing `Response.content` to a file!

I was able to download the PDF you wanted with the following minor modification to your code:
```python
import mechanicalsoup

browser = mechanicalsoup.StatefulBrowser()
browser.open("http://albopretorio.comune.palermo.it/albopretorio/jsp/home.jsp?modo=info&info=servizi.jsp&ARECOD=70&SERCOD=-1&sportello=albopretorio")
browser.follow_link("TD=60")
browser.follow_link("TD=2013")
browser.follow_link("row=0")
response = browser.follow_link("idx=0")

with open('your_filename_here.pdf', 'wb') as f:
  f.write(response.content)
```

**Comment by moy** [comment]
Note that we could easily add a `browser.save(file)` function that would do what the last lines of your code does. Not only this would simplify the user code a bit, but that would also make the feature easier to discover.

Similarly we could have a `browser.download(url or link, file)` function that would do both the `open`/`follow_link` and the download step, ideally streaming directly to disk instead of downloading to memory first.

**Comment by aborruso** [comment]
@moy to add "save" and "download" would be really great.

Thank you very much for all

**Comment by aborruso** [comment]
Thank you very much @hemberger

**Comment by hemberger** [comment]
@aborruso Glad we could help!

@moy Oh, you know what, a `browser.download` method would actually resolve my personal need for a back button in #127. Presumably, if `browser.download` followed a link and saved the result, it would not need to (or want to) update the state of the browser to the followed link (which in many cases would be `None` anyway). You would stay on the current page, much like when you download something from a real web browser. Does that seem reasonable?

**Comment by moy** [comment]
Indeed, `browser.download` could be implemented without touching the state of the browser and that would cover 99 % of the need for a back button.
