### ISSUE TITLE
Shorter getter names

### ISSUE THREAD

**Issue by hemberger** [MechanicalSoup/MechanicalSoup#175]
I've always been a little bothered having to write `browser.get_current_page()` and `browser.get_current_form()`. They're quite lengthy.

With `browser.get_current_page()`, I imagine that `get_page` would suffice (and perhaps there are even shorter aliases we could entertain). There really is not ever another page, so "current" is a superfluous adjective.

With `browser.get_current_form()`, if we're being verbose, then `get_selected_form` seems like it would be more correct and also less confusing to users. However, `get_selected_form` is quite lengthy as well, and I'm not convinced that `get_form` is suitable due to the (rightful) existence of `select_form`.

**Comment by moy** [comment]
Actually, we could/should even use Python's `@property` and avoid getters right away.

**Comment by moy** [comment]
Indeed, I messed up with a push (which I cancelled immediately but it already applied the "fixes" directive).

The current pr is #294.
