### ISSUE TITLE
Pressing a button?

### ISSUE THREAD

**Issue by Spider432** [MechanicalSoup/MechanicalSoup#176]
I am using the latest version of mechanicalsoup, and I am trying to press an HTML element in a form with the class `button`
Here is the html in question: https://hastebin.com/pezajobifa.xml
I'm trying to press the button using this code. 
```
form = browser.select_form('#cart-addf')
form.choose_submit("commit")
link = 'http://testsite.com/shop/bags/add'
browser.submit(form, link)
```
What am I doing wrong?

**Comment by moy** [comment]
You don't need to pass a link to `submit_selected`, it finds it from the "action" field of the form.

Just use `submit_selected`.

**Comment by Spider432** [comment]
Thanks! It works now :)
