### ISSUE TITLE
Problems calling "follow_link" with "url_regex"

### ISSUE THREAD

**Issue by amotl** [MechanicalSoup/MechanicalSoup#177]
Dear Dan and Matthieu,

first things first: Thanks for conceiving and maintaining this great library. We also switched one of our implementations over from "mechanize" as per https://github.com/ip-tools/ip-navigator/commit/a26c3a8a and it worked really well.

When doing so, we encountered a minor problem when trying to call the `follow_link` method with the `url_regex` keyword argument like
```
response = self.browser.follow_link(url_regex='register/PAT_.*VIEW=pdf', headers={'Referer': result.url})
```

This raises the exception
```
TypeError: links() got multiple values for keyword argument 'url_regex'
```

I am are currently a bit short on time, otherwise i would have submitted a pull request without further ado. Thanks a bunch for looking into this issue.

With kind regards,
Andreas.

**Comment by hemberger** [comment]
Hi Andreas,

Thanks for the kind words! Though our thanks must be extended to M. Hickford who was the original author of this library.

From the documentation of [StatefulBrowser.follow_link](https://mechanicalsoup.readthedocs.io/en/stable/mechanicalsoup.html#mechanicalsoup.StatefulBrowser.follow_link),
> If ``link`` doesn't have a *href*-attribute or is None, treat
> ``link`` as a url_regex and look it up with :func:`find_link`.
> Any additional arguments specified are forwarded to this function.

I think this is a bit unclear, but what it really means is this:

If the `link` argument given to `follow_link` is not a bs4 tag, then pass it as the `url_regex` argument to `find_link`.

Therefore, in your call to `follow_link`:
```
response = self.browser.follow_link(url_regex='register/PAT_.*VIEW=pdf', headers={'Referer': result.url})
```
you're essentially making this call to `find_link` (since `link=None`):
```
response = self.browser.find_link(url_regex=None, url_regex='register/PAT_.*VIEW=pdf', headers={'Referer': result.url})
```
To fix your error, you can simply omit `url_regex=` or change it to `link=` in your call to `follow_link`:
```
response = self.browser.follow_link('register/PAT_.*VIEW=pdf', headers={'Referer': result.url})
```

I'm not particularly fond of how all the argument forwarding is set up, and it certainly makes it more difficult to use correctly. At the very least we can be more explicit in the documentation, but perhaps there's also some way to refactor these methods without impacting backwards compatibility too much.

Please let us know if this resolves your problem!

**Comment by amotl** [comment]
Dear Dan,

unfortunately, both variants (as first positional argument or fudged as `link` keyword argument) will raise a `mechanicalsoup.utils.LinkNotFoundError`.

> I'm not particularly fond of how all the argument forwarding is set up

I see your point ;]. That's the reason i was asking for help because my mind signalled it would be too lazy to wrap itself around this ;].


> but perhaps there's also some way to refactor these methods without impacting backwards compatibility too much.

I think there will be a way. Maybe you see a clear way already after letting this sink in for a while or otherwise i might come up with a PR at some time. But please don't hurry, there **is** a work around already in place right now:
```
# Works for now
link = self.browser.find_link(url_regex='register/PAT_.*VIEW=pdf')
return self.browser.open_relative(link['href'], headers={'Referer': result.url})
```

Thanks for your quick response!

Cheers,
Andreas.

**Comment by hemberger** [comment]
I'm surprised (but glad!) that workaround succeeds but my suggestions don't. I think it's clear that I need to do some more digging, so I'll try to come up with a unit test that demonstrates this error. From there it should be pretty simple to suss out what is going on.

Thanks for reporting the issue, and I hope to have more to say soon!

**Comment by amotl** [comment]
Hi again,

#178 addresses the problem in a way i find it reasonable without breaking the test harness. Maybe you want to have a look (and complete it by adding an accompanying unit test)?

Thanks in advance!

With kind regards,
Andreas.

**Comment by moy** [comment]
Seems related to my changes in #184, I'll see if I can do something.

**Comment by moy** [comment]
BTW, about your example setting the `Referer` header, it's now managed by MechanicalSoup (just landed in master, not released yet).

**Comment by amotl** [comment]
Cool, @moy! Thanks for the update, appreciate it.

I am looking forward to test your work on #184 with my amendments to https://github.com/ip-tools/ip-navigator/commit/a26c3a8a as soon as this hits a fresh _MechanicalSoup_ release.

Am i getting it right that i would just have to do
`response = self.browser.download_link(url_regex='register/PAT_.*VIEW=pdf')` then?

**Comment by moy** [comment]
> I am looking forward to test your work ...

Don't hesitate to test _before_ the next release (which we plan to tag as 1.0).

> I  would just have to do ...

Yes, it should just work. But you don't need the `url_regex=` part actually. Just the positional argument works.

**Comment by amotl** [comment]
> Don't hesitate to test before the next release (which we plan to tag as 1.0).

Sure, will be happy to do this. Currently, from your fork/branch located at https://github.com/moy/MechanicalSoup/tree/download-link, right? Or do you plan to merge this branch into mainline soon?

To actually use the `download_link` in my context, the obligatory `filename` argument would however be counterproductive. I added a respective comment at https://github.com/MechanicalSoup/MechanicalSoup/pull/184/commits/ca454ed9#r159693535. Thanks again for looking into this, i hope you appreciate my feedback.

**Comment by moy** [comment]
I should be able to merge it to master soon, but I'm waiting for comments from hemberger.

**Comment by amotl** [comment]
Thanks Matthieu. Works like a charm!
