### ISSUE TITLE
Missing referrer for forms

### ISSUE THREAD

**Issue by tbolender** [MechanicalSoup/MechanicalSoup#179]
I noticed that MechanicalSoup does not include the referrer in the headers when submitting forms. Is there a specific reason for this behavior?

In my case the server side validates the headers and I have to add it manually via
```
browser.session.headers['referer'] = browser.get_url()
```
before every submit.

Changing the behavior, or offering a parameter for this would be nice.

**Comment by moy** [comment]
MechanicalSoup does not do anything about the referer field. I would have bet that requests (the underlying HTTP library) would have set it automatically. If not, we should set it in MechanicalSoup by default (our goal is to mimic the behavior of a browser, which does set it).

**Comment by hemberger** [comment]
Here is a discussion from Requests that describes why they don't set the `referrer` header: https://github.com/requests/requests/issues/2079

I think with MechanicalSoup, which in some sense emulates a "dumb" browser better than Requests, we could reasonably assume that `StatefulBrowser.follow_link` and `StatefulBrowser.open_relative` should set the `referrer` header. Whereas anything that is more directly a wrapper around Requests probably shouldn't (e.g. `StatefulBrowser.open`, `Browser.post`, etc.).

**Comment by giorgiosironi** [comment]
Will this be released before `1.0` (e.g as `0.9.x` or similar)? I have upgraded to the latest stable `0.9.0.post4` but it doesn't have this feature.

**Comment by moy** [comment]
We're planning a release soonish. In the meantime, you can use the master branch, it's very stable (always 100% test coverage and all tests pass).

**Comment by hemberger** [comment]
@giorgiosironi This is now included in the 0.10 release. Cheers!
