### ISSUE TITLE
Crash on input without name in form

### ISSUE THREAD

**Issue by tbolender** [MechanicalSoup/MechanicalSoup#180]
I am currently dealing with a form containing a submit button without a name. When submitting this form (with multiple submit buttons) via
```
browser.submit_selected(btnName='name')
```
this causes a crash in `Form.choose_submit()` since the attribute `name` is not present, [here](https://github.com/MechanicalSoup/MechanicalSoup/blob/master/mechanicalsoup/form.py#L310).

I now that inputs without a name do not make any sense, but it would be nice to harden MechanicalSoup against websites out there in the wild... :)

**Comment by hemberger** [comment]
Thanks for the bug report!

Just to clarify, you're getting a `KeyError: 'name'`?

If so, would you be satisfied with something like:

```python
if inp == submit or ('name' in inp and inp['name'] == submit):
```
