### ISSUE TITLE
Page refresh functionality

### ISSUE THREAD

**Issue by tbolender** [MechanicalSoup/MechanicalSoup#187]
It would be nice to have a refresh functionality which reloads the current page with the same request method and parameters. This is handy when waiting/looking for a certain change on a website to appear.

This would furthermore complete the goal of implementing an actual browser as proposed in #127.

In my opinion saving the last request sent and resending it should be sufficient to implement this functionality. Unfortunately, if I understood correctly, there seems to be no function which every request passes?

**Comment by hemberger** [comment]
Well, all requests are fundamentally a `Requests.PreparedRequest` object, which you can access from `response.request`. We could potentially store the `response` (or the `response.request`) in the browser's state, and then I believe `StatefulBrowser.refresh` would simply be:
```python
def refresh(self):
    self.session.send(self._state.response.request)
```
(with some extra infrastructure to check the result, store the new state, etc.)

Unless there's something I'm missing here, this seems like a pretty easy (and very useful) enhancement.

**Comment by tbolender** [comment]
That sounds nice! I did not know that you could retrieve the request from a response. Thereby also usages of the thin wrappers `get()` and `post()` could easily be handled (this caused some worries when looking into this myself).
