### ISSUE TITLE
Connect to an already running browser

### ISSUE THREAD

**Issue by BeatboxHero** [MechanicalSoup/MechanicalSoup#196]
Does MechanicalSoup have a way to connect to a webpage that is already open in a browser? If so, could I be pointed in the direction of an example? Sorry if this has been answered somewhere. I looked but I couldn't find anything related in documentation or examples.

**Comment by moy** [comment]
By "browser", do you mean a real browser (Firefox, Chrome,...)? If so, then no, there's no simple way to do that with MechanicalSoup. I think Selenium can do that.

**Comment by BeatboxHero** [comment]
Yes, as in a real browser. Unfortunately, Selenium doesn't work for what I am trying to accomplish either. Thanks for the quick answer!
