### ISSUE TITLE
When control values are set dynamically via javascript 

### ISSUE THREAD

**Issue by luisfalconeri** [MechanicalSoup/MechanicalSoup#198]
As with this link below: 
https://www.residentadvisor.net/submit-event.aspx

The values for the field city are set dynamically after the country has been set: I was not able to find a solution in the relevant documentation. Is there one? Sorry if it's a silly question. Thanks

**Comment by moy** [comment]
MechanicalSoup does not do JavaScript. You may want to look at Selenium instead. See the FAQ:

http://mechanicalsoup.readthedocs.io/en/stable/faq.html#how-does-mechanicalsoup-compare-to-the-alternatives
