### ISSUE TITLE
Add Docker images?

### ISSUE THREAD

**Issue by hemberger** [MechanicalSoup/MechanicalSoup#200]
Should we add Docker images for easy use of MechanicalSoup? I find that, at least for Alpine Linux, it's not completely trivial to create an image that can `pip install mechanicalsoup` (and the non-alpine python images I find to be too large to be practically usable).

**Comment by moy** [comment]
Why not. It should be rather straightforward to do (essentially turning the `install` part of our `.travis.yml` file into a `Dockerfile`).

Out of curiosity, what are the difficulties in setting up MechanicalSoup on Alpine Linux?

**Comment by hemberger** [comment]
It's actually not too bad, but here's the `Dockerfile` I was able to get working with alpine linux:
```
FROM python:3-alpine

RUN apk add --no-cache g++ libxml2 libxslt-dev \
	&& pip install mechanicalsoup \
	&& apk del g++
```

This gets you a 130MB image (whereas the full python images are usually 600-700MB).

**Comment by moy** [comment]
Looks good to me.

**Comment by hemberger** [comment]
Closing this to avoid introducing additional maintenance. This issue will serve as a reference for anyone who wants to create their own image, but it's likely that any user would want more than just MechanicalSoup in their image.
