### ISSUE TITLE
LinkNotFoundError should not inherit from BaseException

### ISSUE THREAD

**Issue by gronka** [MechanicalSoup/MechanicalSoup#203]
Hello,

I have code that performs many tests, reporting which tests failed. We therefore implement a try-catch such as

```python
try:
    run_test()
except Exception:
    msg = traceback.format_exc() 
    report_failure()
```

LinkNotFoundError is not caught by this because it inherits from BaseException.

Inheriting from BaseException is not recommended in the docs: https://docs.python.org/3/library/exceptions.html

I'd like too see this change, or if there is a reason for it I'm curious to hear it.

**Comment by moy** [comment]
Indeed, I'm guilty of not having read the docs well enough :-(.

If the only choices were to keep the code as-is or to change the base class to `Exception`, I'd favor breaking backward compatibility too. But there may be another option: keep both base classes. This fixes @gronka's use-case, but still works for people expecting `except BaseException` to catch it:

```
--- a/mechanicalsoup/utils.py
+++ b/mechanicalsoup/utils.py
@@ -1,4 +1,4 @@
-class LinkNotFoundError(BaseException):
+class LinkNotFoundError(Exception, BaseException):
     """Exception raised when mechanicalsoup fails to find something.
 
     This happens in situations like (non-exhaustive list):
@@ -12,5 +12,11 @@ class LinkNotFoundError(BaseException):
     * The user tried to fill-in a field which doesn't exist in a form
       (e.g. browser["name"] = "val" with browser being a
       StatefulBrowser).
+
+    For backward compatibility reasons, this class derives from both
+    ``Exception`` and ``BaseException``, but it should in theory
+    inherit only from ``Exception``. Do not rely on ``BaseException``
+    to be a base class in your code as it may be removed in the
+    future.
     """
     pass
```

It's a little ugly, but it should fix the issue, and keeps the door open to removing the incorrect base class in the future if we really find it too ugly. What do you think?

**Comment by hemberger** [comment]
I'm not sure that inheriting from both classes has any benefit. There are two issues that I see:

1. If you are expecting a `BaseException`, then letting `LinkNotFoundError` inherit only from `Exception` still achieves that because `Exception` inherits from `BaseException`.

2. If you are NOT expecting an `Exception`, then letting `LinkNotFoundError` inherit from `Exception` (instead of _or_ in addition to `BaseException`) still breaks backwards compatibility. The following code would behave differently after such a change:
```python
try:
    raise LinkNotFoundError
except Exception as e:
    # do something
```
This is likely a pathological scenario, but at the very least would need to be documented if we break it.

**Comment by moy** [comment]
@hemberger : you are right. And I wrote my nonsense message _after_ coffee ;-).

There's another potential change for users if we change the base class:

```
try:
    ...
except Exception:
    <special case for Exception>
except BaseException:
    <other treatment for BaseException>
```

But I think we can safely consider this as pathological scenario (I can't think of any good reason to write this).

So, changing `BaseException` to `Exception` seems the right thing to do (together with a note in the ChangeLog obviously).
