### ISSUE TITLE
Handle forms with multiple submits that have the same name

### ISSUE THREAD

**Issue by zen4ever** [MechanicalSoup/MechanicalSoup#207]
On some websites submit elements have the same name. As it currently works with MechanicalSoup, it just throws exception when I'm trying to choose one of them by name.

Possible solutions:
1. Allow to choose by other attributes, like "select_form" currently works
2. Allow to specify index when multiple elements found "nr=0"

**Comment by hemberger** [comment]
Thanks for the bug report! I believe this would be solved by #160, but there were some complications that prevented us from immediately merging it. I'll try to get back to this soon.

**Comment by zen4ever** [comment]
Thanks @hemberger, I don't remember exactly how I solve it, but I believe I found the workaround along the lines of your example.
