### ISSUE TITLE
httpbin tests require network access

### ISSUE THREAD

**Issue by sbraz** [MechanicalSoup/MechanicalSoup#215]
Hi,
It seems that tests require network access. You modified pytest-httpbin to make it connect to the real website instead of the local version, why is that?
The Gentoo sandbox doesn't allow network access so this causes the tests to fail:
```
E           requests.exceptions.ConnectionError: HTTPConnectionPool(host='httpbin.org', port=80): Max retries exceeded with url: /forms/post (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8ca79b8ac8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

```

Here is the full [build.log](https://github.com/MechanicalSoup/MechanicalSoup/files/2141788/build.log).

**Comment by hemberger** [comment]
I see only three tests that fail when I disconnect my 

```
tests/test_browser.py::test__request FAILED
tests/test_browser.py::test__request_file FAILED
tests/test_stateful_browser.py::test_new_control FAILED
```
It should be fairly simple to fix these, so I'll take a look at it now.

**Comment by sbraz** [comment]
test_new_control is using a hardcoded http://httpbin.org URL so it's quite easy to fix. The other two are using a form, I'm not sure how you can reinject the local httpbin URL into it.

**Comment by sbraz** [comment]
Ah, we can probably replace the URL inside form_html and then form_html.format(httpbin.url)

**Comment by hemberger** [comment]
Indeed! Thanks for reporting the issue.

**Comment by sbraz** [comment]
That branch works for me :) When can we hope to see a new release,

**Comment by hemberger** [comment]
I can make time to do a release next week, but I'll have to coordinate with @moy first. (@moy: I sent you a message on Gitter, but we can coordinate wherever is most convenient for you :)
