### ISSUE TITLE
TextArea add new line

### ISSUE THREAD

**Issue by Neuroforge** [MechanicalSoup/MechanicalSoup#221]
Hello,

I am trying to add a new line to text put into a TextArea.

I've tried the standard python "\n" and "\r\n" but no luck. It prints the characters to the textarea as well.

Regards,

Daniel

**Comment by hemberger** [comment]
Hi, thanks for your question!

Could you describe what you're using to check to see what the content of the `textarea` is? Are you checking it locally, or viewing the response from the remote server?

Doing just a simple test with:
```python
form['textarea_name'] = 'some\ntext'
form.print_summary()
```
seemed to give me the newline I expected. I would have only expected a literal `\n` if you used `\\n` to escape the backslash.

Another option to try in the meantime might be:
```python
form['textarea_name'] = """some
text"""
form.print_summary()
```

Anyway, let us know!

**Comment by moy** [comment]
Hi,

@Neuroforge: can you give us more info about what you did so that we can help you? Without more info, I'll close the issue.

Thanks,
