### ISSUE TITLE
Send an non-form

### ISSUE THREAD

**Issue by CaioFrancisco** [MechanicalSoup/MechanicalSoup#241]
How do i send a non-form in mechanicalsoup?

**Comment by moy** [comment]
What do you mean by non-form? Can you give an example?

**Comment by CaioFrancisco** [comment]
Let's take the login page of hotmail for example. It have input where not have form.

**Comment by moy** [comment]
As I mentioned in the comments of your [StackOverflow question](https://stackoverflow.com/questions/52453190/mechanicalsoup-not-selecting-a-non-form-input) (and as @hemberger guessed), the page you're trying to browse relies on JavaScript far too much for MechanicalSoup.

I'm closing this issue, if you don't think we answered your question or if you have more information to share, feel free to add comments and/or edit your StackoverFlow question.
