### ISSUE TITLE
select input in the form

### ISSUE THREAD

**Issue by erichuang2015** [MechanicalSoup/MechanicalSoup#243]
hello

how to deal with the form with select input element

<select name="mylist">
                    <option selected="selected">first</option>
                    <option>two</option>
                    <option>threee</option>
                    <option>four</option>
</select>

errors throw when try 

 response = browser.submit_selected()

option.attrs["selected"] = "selected"
AttributeError: 'NoneType' object has no attribute 'attrs'

**Comment by hemberger** [comment]
Reading this issue
It starts to sound like haiku
More details needed

**Comment by hemberger** [comment]
Since this report seems to have become inactive, I'm going to close it for now. Feel free to re-open if you can provide more information.
