### ISSUE TITLE
Tag type maching case sensitive

### ISSUE THREAD

**Issue by Pimmetje** [MechanicalSoup/MechanicalSoup#245]
When the form uses upper casing the matching would fail.

https://github.com/MechanicalSoup/MechanicalSoup/blob/5926d0efd887097f9da56241ae945c4d5a81d8ba/mechanicalsoup/browser.py#L166

Suggest adding .lower()
`if tag.get("type").lower() in ("radio", "checkbox"):`

**Comment by moy** [comment]
Not sure the upper-case version is correct HTML, but anyway, we should be tolerant in what we accept.

Patch follows.

**Comment by moy** [comment]
The stackoverflow link is about tag names, but the issue here is about the attribute's content.

**Comment by Pimmetje** [comment]
Your right: That asks for more research.
"Attribute names are case-insensitive, but attribute values may be case-sensitive." [1]
So i guess you could be right. 
If i read [2] i get the feeling this reference is more like u have to use the same casing in the document. But i can't find a reference stating the case requirements for basic attributes. So i think it's best to assume they could be anything.

[1] http://www.htmlhelp.com/reference/html40/structure.html#attributes
[2] http://www.htmlhelp.com/reference/html40/values.html

**Comment by moy** [comment]
Anyway, "how HTML should be?" is not very important in real life for tools like MechanicalSoup. "How the HTML you're parsing is?" is the right question (somehow, well-designed websites have a proper API to avoid having to parse HTML, so they don't need MechanicalSoup ...).
