### ISSUE TITLE
Question: example.py seems to broken (again)?

### ISSUE THREAD

**Issue by clipka** [MechanicalSoup/MechanicalSoup#255]
Hi,

I tried to run the example as is without success.

Traceback (most recent call last):
  File "example.py", line 37, in <module>
    assert page.select(".logout-form")
AssertionError

Does anyone else has the same problem? Thanks for help!

Here is the environment I use:

pip3 show mechanicalsoup
Name: MechanicalSoup
Version: 0.11.0
Summary: A Python library for automating interaction with websites
Home-page: https://mechanicalsoup.readthedocs.io/
Author: UNKNOWN
Author-email: UNKNOWN
License: MIT
Location: /usr/local/lib64/python3.7/site-packages
Requires: requests, beautifulsoup4, lxml, six

**Comment by moy** [comment]
It works for me. Just re-tested to be sure:

```
$ python3 example.py moy
Please enter your GitHub password: 
GitHub
```

OTOH, I get the same failure as you if I enter an incorrect login or password.

**Comment by clipka** [comment]
Oooh. I triple checked my input (and changed my pw in between)... and suddenly it works... Sorry for annoying you. And thanks for your support.
Now it's time to explore the module :-)
