### ISSUE TITLE
Tests broken after pip upgrade

### ISSUE THREAD

**Issue by hemberger** [MechanicalSoup/MechanicalSoup#257]
The tests are failing on Travis now due to a change in one of our dependencies. I updated my pip packages and can confirm that they went from passing to failing.

A cursory look at the failures seem to indicate that some lists are now ordered differently. I will investigate to see if we should expect a different order, or if it's an issue of some randomness due to, e.g., assuming an ordering of dictionary elements.

It's not entirely helpful, but here's the original (passing) and newest (failing) packages I was using:
```
Name           Current Version Latest Version Home Page                                                
-------------- --------------- -------------- ---------------------------------------------------------
wheel          0.31.1          0.32.3         https://github.com/pypa/wheel                            
urllib3        1.23            1.24.1         https://urllib3.readthedocs.io/                          
twine          1.11.0          1.12.1         https://twine.readthedocs.io/                            
tqdm           4.26.0          4.29.1         https://github.com/tqdm/tqdm                             
Sphinx         1.7.5           1.8.3          http://sphinx-doc.org/                                   
six            1.11.0          1.12.0         https://github.com/benjaminp/six                         
setuptools     40.2.0          40.6.3         https://github.com/pypa/setuptools                       
requests       2.19.1          2.21.0         http://python-requests.org                               
requests-mock  1.5.0           1.5.2          https://requests-mock.readthedocs.io/                    
raven          6.9.0           6.10.0         https://github.com/getsentry/raven-python                
pytz           2018.4          2018.9         http://pythonhosted.org/pytz                             
pytest         3.6.1           4.1.1          https://docs.pytest.org/en/latest/                       
pytest-flake8  1.0.1           1.0.3          https://github.com/tholo/pytest-flake8                   
pytest-cov     2.5.1           2.6.1          https://github.com/pytest-dev/pytest-cov                 
pyparsing      2.2.0           2.3.1          https://github.com/pyparsing/pyparsing/                  
Pygments       2.2.0           2.3.1          http://pygments.org/                                     
pyflakes       1.6.0           2.0.0          https://github.com/PyCQA/pyflakes                        
pycparser      2.18            2.19           https://github.com/eliben/pycparser                      
pycodestyle    2.3.1           2.4.0          https://pycodestyle.readthedocs.io/                      
py             1.5.3           1.7.0          http://py.readthedocs.io/                                
prompt-toolkit 1.0.15          2.0.7          https://github.com/jonathanslenders/python-prompt-toolkit
pluggy         0.6.0           0.8.1          https://github.com/pytest-dev/pluggy                     
pkginfo        1.4.2           1.5.0.1        https://code.launchpad.net/~tseaver/pkginfo/trunk        
pip            9.0.1           18.1           https://pip.pypa.io/                                     
pickleshare    0.7.4           0.7.5          https://github.com/pickleshare/pickleshare               
parso          0.2.1           0.3.1          https://github.com/davidhalter/parso                     
packaging      17.1            18.0           https://github.com/pypa/packaging                        
more-itertools 4.2.0           5.0.0          https://github.com/erikrose/more-itertools             
MarkupSafe     1.0             1.1.0          https://www.palletsprojects.com/p/markupsafe/            
lxml           4.2.1           4.3.0          http://lxml.de/                                          
jedi           0.12.0          0.13.2         https://github.com/davidhalter/jedi                      
itsdangerous   0.24            1.1.0          https://palletsprojects.com/p/itsdangerous/              
ipython        6.4.0           7.2.0          https://ipython.org                                      
imagesize      1.0.0           1.1.0          https://github.com/shibukawa/imagesize_py                
idna           2.7             2.8            https://github.com/kjd/idna                              
flake8         3.5.0           3.6.0          https://gitlab.com/pycqa/flake8                          
coverage       4.5.1           4.5.2          https://bitbucket.org/ned/coveragepy                     
click          6.7             7.0            https://palletsprojects.com/p/click/                     
certifi        2018.8.24       2018.11.29     https://certifi.io/                                      
beautifulsoup4 4.6.0           4.7.1          http://www.crummy.com/software/BeautifulSoup/bs4/        
attrs          18.1.0          18.2.0         https://www.attrs.org/                                   
atomicwrites   1.1.5           1.2.1          https://github.com/untitaker/python-atomicwrites         
alabaster      0.7.10          0.7.12         https://alabaster.readthedocs.io                         
```

**Comment by hemberger** [comment]
Confirmed that it's only an ordering issue. If I replace
```python
assert (query == expected)
```
with
```python
assert (sorted(query) == sorted(expected))
```
then all the tests pass.

This change was precipitated by a new implementation of CSS selectors in BeautifulSoup4 in version 4.7:
>Beautiful Soup's CSS Selector implementation has been replaced by a
  dependency on Isaac Muse's SoupSieve project (the soupsieve package
  on PyPI). The good news is that SoupSieve has a much more robust and
  complete implementation of CSS selectors, resolving a large number
  of longstanding issues. The bad news is that from this point onward,
  SoupSieve must be installed if you want to use the select() method.
>
>You don't have to change anything lf you installed Beautiful Soup
  through pip (SoupSieve will be automatically installed when you
  upgrade Beautiful Soup) or if you don't use CSS selectors from
  within Beautiful Soup.

I am having trouble finding a reference, but I believe that one of the longstanding issues was the way that the original bs4 implementation returned results (they weren't ordered by location on the page -- _I think_).

This is consistent with the following test. Given the following HTML:

```html
<table></table>
<p></p>
<div></div>
<span></span>
```

Result with bs4 4.7.1 (ordered by page elements):
```python
>>> bs4.BeautifulSoup(html).select("span, div, p, table")
[<table></table>, <p></p>, <div></div>, <span></span>]
```
Result with bs4 4.6.0 (ordered by CSS selector terms):
```python
>>> bs4.BeautifulSoup(html).select("span, div, p, table")
[<span></span>, <div></div>, <p></p>, <table></table>]
```

So I think this is great news for us overall, since browsers order their requests in the same way as bs4 4.7! But it leaves us with the following question:
* How do we modify the test?

My recommendation is to reorder the expected result so that it is page-ordered, and then perhaps check the result with something like
```python
from distutils.version import StrictVersion
if StrictVersion(bs4.__version__) >= StrictVersion('4.7.0'):
    assert query == expected
else:
    assert sorted(query) == sorted(expected)
```

This will keep the test as stringent as possible while still permitting backwards compatibility for anyone running tests with an older bs4.

**Comment by facelessuser** [comment]
Hi,  I'm the author of SoupSieve, the new library that provides BeautifulSoup 4.7.0+ CSS selector support. I've been checking out issues now and then on GitHub that have "soupsieve" in them in order to get feedback that maybe isn't making it back to me. I've been learning a lot through this process as to how quirky the old select method was.

Just here to confirm that SoupSieve does return things in document order, and that behavior can be relied on moving forward.

It seems most people who use BeautifulSoup have grown to rely on `find` and `find_all` instead of `select` and `select_one`,  which I can't blame them as the old `select` was very unreliable and quirky, but hopefully, for those who do use `select` they will find the behavior very solid and feature rich moving forward.

The big differences are that it it does return things in document order and selectors should follow the CSS spec in regards to syntax and usually in behavior as much as possible in a non-browser environment. There is no longer a restriction in selector complexity, and in HTML and XHTML documents, it will mimic browser behavior, for example: `type` attributes are treated case insensitively except when the CSS4 syntax for forced sensitivity is used `[type=submit s]`.

As with most projects, I assume MechanicalSoup relies heavily upon `find` and `find_all`, so the ordering test is most likely the biggest impact that should be experienced, but if this project happens to stumble on some issues, please do file an issue.

**Comment by hemberger** [comment]
@facelessuser Hi, thanks for the confirmation and for your work on SoupSieve! So far the changes to CSS selectors brought in with bs4 4.7.0+ have been a great boon to us, resolving a longstanding consistency issue between MechanicalSoup and real browser behavior. If we run into any related issues going forward, I'll make sure the feedback reaches you.

**Comment by moy** [comment]
@facelessuser Thanks also for taking care of reaching your users without waiting for them to come to you. Very much appreciated indeed!

**Comment by facelessuser** [comment]
No problem.  The ordering difference was something new to me.  I guess I had just assumed the old `select` method followed the logical flow of iterating the descendants, but I guess not. So I guess an unexpected bonus 🙂 .
