### ISSUE TITLE
Cannot submit form with multiple identical submits

### ISSUE THREAD

**Issue by ricecooker** [MechanicalSoup/MechanicalSoup#264]
When I have a form like:

```
<form action="#" method="POST" name="blah">
  <input type="submit" name="search" value="Search"/>
  <input type="submit" name="search" value="Search"/>
</form>
```
There isn't a way to submit the form. It will *always* raise a `LinkNotFoundError`.

Around form.py:333 I'd do 
```
if inp == submit and found: 
  del inp['name']
```

**Comment by amrit94** [comment]
Please add button name  in the HTML like:
```
<input type="submit" value="Submit" name ='button1'>
<input type="submit" value="Submit" name ='button2'>
```
And in mechanicalsoup submit using btnName = 'buttonName'

> response = browser.submit_selected(btnName='button1')

**Comment by nk9** [comment]
Thanks for fixing this. The last release was from a year ago, though. If I need this now, what's the recommended branch? Just… master? ***gulp***

**Comment by hemberger** [comment]
I'm sure we could come up with a new release on fairly short order. I'll talk to @moy and we'll keep you posted.

**Comment by nk9** [comment]
That would be swell, thanks.

For others who may be running into the problem and are using v0.11.0 or earlier, I have found a simple solution:

```
submitEls = browser.get_current_page().find_all(type='submit')

# Remove excess submit elements
for index, submitEl in enumerate(submitEls):
	if index > 0:
		submitEl.extract()
```
