### ISSUE TITLE
No form id,class,name just method="post" and novalidate

### ISSUE THREAD

**Issue by raku666** [MechanicalSoup/MechanicalSoup#266]
Hi, it cant seem to detect the only form on the site. the form only had method="post" and novalidate

is it possible to submit a form with just method and novalidate? please help me.

br.select_form() doesnt work .

**Comment by hemberger** [comment]
Hi, thanks for your question. Please see [this FAQ](https://mechanicalsoup.readthedocs.io/en/stable/faq.html#form-submission-has-no-effect-or-fails) for the answer.
