### ISSUE TITLE
No valid element named q

### ISSUE THREAD

**Issue by tbhaxor** [MechanicalSoup/MechanicalSoup#287]
The reproduction code is

```py
url = "http://dramaonline.pk/"
from mechanicalsoup import StatefulBrowser # importing the browserb
browser = StatefulBrowser() # creating browser with history enabled
browser.open(url) # opening the url
browser.select_form("#search_box") # selecting the form
browser["q"] = "TEST_tbhax0r" # sending the values
browser.submit_selected() # submit the selected form
```

**Error**
```
---------------------------------------------------------------------------
LinkNotFoundError                         Traceback (most recent call last)
<ipython-input-39-6637ec083075> in <module>
----> 1 browser["q"] = "TEST_tbhax0r" # sending the values
      2 browser.submit_selected() # submit the selected form

/usr/lib/python3.7/site-packages/mechanicalsoup/stateful_browser.py in __setitem__(self, name, value)
    101         See :func:`Form.__setitem__`.
    102         """
--> 103         self.get_current_form()[name] = value
    104 
    105     def new_control(self, type, name, value, **kwargs):

/usr/lib/python3.7/site-packages/mechanicalsoup/form.py in __setitem__(self, name, value)
    223         :code:`form["name"] = "value"` calls :code:`form.set("name", "value")`.
    224         """
--> 225         return self.set(name, value)
    226 
    227     def set(self, name, value, force=False):

/usr/lib/python3.7/site-packages/mechanicalsoup/form.py in set(self, name, value, force)
    264             self.new_control('text', name, value=value)
    265             return
--> 266         raise LinkNotFoundError("No valid element named " + name)
    267 
    268     def new_control(self, type, name, value, **kwargs):

LinkNotFoundError: No valid element named q
```

**Comment by moy** [comment]
The form is not named `#search_box`, but `search`, so your `select_form` line is wrong. Admittedly, MechanicalSoup could have errored-out at this line instead of the next one.

**Comment by hemberger** [comment]
@moy We had a brief discussion about this in my draft of properties, for a proposed `get_selected_form` method to raise an exception if no form had been selected. Are your feelings about this still the same as in https://github.com/MechanicalSoup/MechanicalSoup/pull/185#issuecomment-355507761?

**Comment by moy** [comment]
It's not the same situation here: there's no getter involved in the user code. The `select_code` line could/should have failed, and the `__setitem__` could have given a better error message (it does error out anyway).

**Comment by hemberger** [comment]
Hmm, now I'm confused. I always thought that `select_form` raised a `LinkNotFoundError` if the selector doesn't exist. How does the code in the op get past `browser.select_form("#search_box")` then?

I haven't tested this myself, but it looks like `test_launch_browser` covers this case. What am I missing here? :)

**Comment by moy** [comment]
The HTML is:

```
        	<form id="search" action="/search.php" method="GET">
              <span role="status" aria-live="polite" class="ui-helper-hidden-accessible" style="background-color: red;"></span>
              <input id="search_box" type="text" value="" placeholder="Search Dramas Online Here" class="autocomplete ui-autocomplete-input" name="q" autocomplete="off">
              <!--<input type="submit" value="Search" style="display:none;"/>-->
              <button style="padding: 5px; position: absolute; width: 100px; height: 40px; top: -2px; right: 0px; background-color: transparent; border: medium none;" class="search_btn" onClick="document.getElementById('search').submit();"></button>
            </form>
```

There's an element with the right name, but it's not a `form`. I didn't try myself, though.

**Comment by hemberger** [comment]
Aha, I see. So perhaps we could verify that the selected element is actually a form?

**Comment by moy** [comment]
Yes, that's what I had in mind.

**Comment by tbhaxor** [comment]
> The form is not named `#search_box`, but `search`, so your `select_form` line is wrong. Admittedly, MechanicalSoup could have errored-out at this line instead of the next one.

So this module actually load the form on the basis of `id`, that what could conclude. 
What if there is no id? does it support getting element by xpath or css selector ?

**Comment by tbhaxor** [comment]
> The form is not named `#search_box`, but `search`, so your `select_form` line is wrong. Admittedly, MechanicalSoup could have errored-out at this line instead of the next one.

So this module actually loads the form on the basis of `id`. 
What if there is no id? does it support getting element by xpath or css selector ?

**Comment by moy** [comment]
See https://mechanicalsoup.readthedocs.io/en/stable/mechanicalsoup.html#mechanicalsoup.StatefulBrowser.select_form : it does support CSS selectors.

You can also use any way BeautifulSoup provides to select a `bs4.element.Tag` object.

**Comment by tbhaxor** [comment]
Well, I chose selenium headless over mechanicasoup. BTW thanks
