### ISSUE TITLE
How to log into website if input don't have a name?

### ISSUE THREAD

**Issue by Jaco020** [MechanicalSoup/MechanicalSoup#289]
I am currently working on program that log into website. 
I test it on different sites and it works good, but on one site i found 
password input without name. What should i do to log into that site?

Here is my program

    browser = mechanicalsoup.StatefulBrowser()
    browser.open("website_url")
    browser.select_form("form")
    browser["login_input_name"] = "login"
    browser["pass_input_name"] = "pass"

    browser.submit_selected()

    print(browser.get_url())
    print(browser.get_current_page())

password input:
<input` type="password" class="defbtn_on_enter input_text" id="pass" value="" style="width: 20ex; cursor: auto;" autocomplete="off">

**Comment by moy** [comment]
https://stackoverflow.com/questions/52585753/using-mechanicalsoup-to-set-value-of-form-element-w-o-a-name

**Comment by Jaco020** [comment]
Thank. I'll give it a try
