### ISSUE TITLE
Uppercase Radio types not being checked

### ISSUE THREAD

**Issue by MNoumanAbbasi** [MechanicalSoup/MechanicalSoup#291]
Trying to check a radio type in forms with type "RADIO" does not work; it is not checked.
Trying this on [this test site](http://httpbin.org/forms/post).
It will work if we have a combination of uppercase and lowercase radio types like in the test_form file. For example, this will work:
`<p><input name="size" type="RADIO" value="small">Small</p>`
`<p><input name="size" type="radio" value="medium">Medium</p>`
`<p><input name="size" type="radio" value="large">Large</p>`
But the above will not work if all types are set to "RADIO" i.e. in uppercase.

**Comment by moy** [comment]
The test site you point to is the one we use for testing, and does not have uppercase RADIO inputs. Can you provide an actual test case?

I'm actually surprised by the behavior you describe. The actual cause is very likely something else.

**Comment by MNoumanAbbasi** [comment]
I downloaded the test site I pointed out above. Changed all the radio types from lowercase to uppercase (i.e. type="RADIO"), and then ran the site on localhost server.
The code I wrote:
```
import mechanicalsoup
browser = mechanicalsoup.StatefulBrowser()
browser.open('http://127.0.0.1:5500/post.html')
browser.select_form()
browser['size'] = 'medium'
browser.get_current_form().print_summary()
browser.submit_selected()
```
This, however did not 'check' the radio element, instead it changed its value to this:
```
<input name="size" type="RADIO" value="medium"/>
<input name="size" type="RADIO" value="medium"/>
<input name="size" type="RADIO" value="large"/>
```
When I revert back to using the original lowercase (type="radio"), it works as expected:
```
<input name="size" type="radio" value="small"/>
<input checked="" name="size" type="radio" value="medium"/>
<input name="size" type="radio" value="large"/>
```

I'm not entirely sure, but this issue may be related to a [previous one](https://github.com/MechanicalSoup/MechanicalSoup/issues/245) (245).

**Comment by moy** [comment]
I can't reproduce, and the behavior you're observing is the one of old MechanicalSoup version. Note that the fix is not yet in a released version, but you can use the master branch if you need this fix.

**Comment by MNoumanAbbasi** [comment]
Oh right. Sorry for the misunderstanding, I'm new to open source. And yes, I was using the release version.
