### ISSUE TITLE
test_enctype_and_file_submit fails for some dependency versions

### ISSUE THREAD

**Issue by hemberger** [MechanicalSoup/MechanicalSoup#299]
I'm getting an error for the following test in a local build:

tests/test_browser.py::test_enctype_and_file_submit[multipart/form-data-False-<input name="pic" type="file" />] FAILED

```
>               assert found_in == "files"
E               AssertionError: assert 'form' == 'files'
E                 - form
E                 + files
```

This build uses the following dependency versions:

requests (2.21.0)
beautifulsoup4 (4.7.1)

Note that TravisCI is using `requests-2.22.0` and `beautifulsoup4-4.8.0`.

**Comment by moy** [comment]
Looks very much like the issue we had with httpbin which shows empty files in the wrong section for some version of Werkzeug (the underlying backend dealing with HTTP). We tried writing the test in a way that works for both the broken and the non-broken httpbin, but apparently we didn't. If I'm guessing correctly, it's only an issue with the tests, not with the actual code.

**Comment by hemberger** [comment]
I am closing this since it is an issue with an old version of a dependency that's only used in tests.
