### ISSUE TITLE
Translation documents

### ISSUE THREAD

**Issue by lionking6792** [MechanicalSoup/MechanicalSoup#302]
It might be helpful to get documents translated version.
cause, many Asians look forward to your 'MechanicalSoup'!

Do you have or Do you need documents translations?

Thanks for reading :)

**Comment by moy** [comment]
I wouldn't be opposed to a translated documentation, but honestly I doubt many people are both fluent enough in Python to use MechanicalSoup and not fluent enough in English to read the documentation (possibly via the help of an automatic translator).

And obviously, I can't commit to maintain a documentation in any Asian language ;-).

**Comment by lionking6792** [comment]
I just asked cause, I'm interested in Translating documents to Korean, cause I was translating some docs for my Korean friends.

I'll pr to you later, if you are intersted translated Korean docs later, you can consider merge to it!

Thanks for comment!

**Comment by hemberger** [comment]
Closing this due to age, but please feel free to submit a PR if you would like to provide translated documents!
