### ISSUE TITLE
Upload a file

### ISSUE THREAD

**Issue by Alexinho3** [MechanicalSoup/MechanicalSoup#306]
Is there a possible way to upload a file using MechanicalSoup?

Of course this is wrong in the manual ```form.set("tagname") = path_to_local_file```, but also ```form.set("tagname", path_to_local_file)``` does not work for me.

Thank you

**Comment by moy** [comment]
Hi,

Thanks for your interest in MechanicalSoup.

Yes, there is a way and apparently you found it in the manual. If you want help to solve your issue, you'll need to provide more details on what you did and why you consider that it does not work.

**Comment by moy** [comment]
Hi,

Without more information, we can't help you, therefore I'm closing the issue. Feel free to re-open with additional info if needed.
