### ISSUE TITLE
can't use find_all() function to find tags in <svg>...</svg>

### ISSUE THREAD

**Issue by tirajetw** [MechanicalSoup/MechanicalSoup#307]
In beautifulsoup fix by 

    from bs4 import BeautifulSoup
    soup = BeautifulSoup('<svg></svg>', 'xml')
    print(soup)

from [https://stackoverflow.com/questions/49359684/python-beautifulsoup-adds-html-tags-to-svg](url)

but I don't know to use it with MechanicalSoup. 
Thanks for your help.

**Comment by hemberger** [comment]
Sorry for the delayed response! The [StatefulBrowser documentation](https://mechanicalsoup.readthedocs.io/en/stable/mechanicalsoup.html#statefulbrowser) gives an example of how to instruct Beautifulsoup to use a specific parser. So to use the `xml` parser, you would want something like:

```python
browser = mechanicalsoup.StatefulBrowser(
    soup_config={'features': 'xml'},  # Use the xml parser
)
```
Please feel free to reopen this ticket if you encounter any further issues. Good luck!
