### ISSUE TITLE
How to add proxy support to mechanicalsoup?

### ISSUE THREAD

**Issue by freeway58** [MechanicalSoup/MechanicalSoup#308]
I use the proxy this way, it seem didn't work.

```
import mechanicalsoup

proxies = {
    "http": "socks5://127.0.0.1:49260",
    "https": "socks5://127.0.0.1:49260"
}
url = 'https://whatismyip.com/'
browser = mechanicalsoup.StatefulBrowser()

browser.session.proxies = proxies   # This seem can't work

page = browser.open(url)  #, verify=False
print(page)
print(page.text)
```

Where's a working demo about this? Thank you!

**Comment by hemberger** [comment]
Hi there! MechanicalSoup is a thin wrapper around the powerful Requests module. Looking at their [proxies documentation](https://requests.readthedocs.io/en/master/user/advanced/#proxies), I would have expected your example to work, but another approach to try might be:
```python
page = browser.open(url, proxies=proxies)
```
Give it a try and let us know how it goes.

**Comment by freeway58** [comment]
Hi @hemberger ,  use this way can't got the right proxy address, it also shows my real ip.

**Comment by hemberger** [comment]
This sounds like it is a question for the people over at [Requests](https://github.com/psf/requests) then. MechanicalSoup does nothing with proxies besides forwarding the arguments. Sorry I can't be of more help!

**Comment by hemberger** [comment]
Closing this due to age, but please feel free to update us if you found a resolution to your issue!
