### ISSUE TITLE
Why is Pypi version not current? 

### ISSUE THREAD

**Issue by dahifi** [MechanicalSoup/MechanicalSoup#314]
Was going crazy trying to follow the examples and getting errors like StatefulBrowser doesn't have a Forms attribute, then found that the 0.12 version tag is two years behind the current master? 

Just curious what the recommended installation is. Couldn't get pipenv to add the git repo, so added it as a submodule just so I can proceed.

**Comment by hemberger** [comment]
Hi, thanks for your question.

When looking at the documentation, make sure you use the "stable" version: https://mechanicalsoup.readthedocs.io/en/stable/. You might have been looking at "latest", which is the documentation for the development version (not on PyPI).

Version 0.12.0 was released on Aug 19, 2019, so only about 6 months ago. We will release the development version (1.0.0) once the current changes have had some time to soak.

Installation instructions are available in our README (https://github.com/MechanicalSoup/MechanicalSoup#installation). If anything is unclear there, we would be grateful for your help in clarifying it. Thanks!

**Comment by dahifi** [comment]
Couldn't recreate the issue. Must have been going off of old documentation. Removed the git submodule and pulled down via pipenv and verified it's version 0.12. 

Thanks.

**Comment by hemberger** [comment]
I'm glad to hear it's working for you. Thanks for letting us know!
