### ISSUE TITLE
get input value

### ISSUE THREAD

**Issue by ism** [MechanicalSoup/MechanicalSoup#322]
Hi there everyone!

I am trying to get input form value of selected form. I came up with this

```
b = mechanicalsoup.StatefulBrowser()
...
firstname = b.get_current_form().form.find('input', {'name': 'firstname'})['value']

```
Is there any better way to do this?
As a suggestion, maybe we can get values from forms as easy as setting them?
In my case it would look like that:

`firstname = b['firstname']`

**Comment by moy** [comment]
Indeed, we do have `__setitem__` methods in `StatefulBrowser` and `Form` to allow the `[...] = ...` syntax, but no `__getitem__` to read from a field. It should be rather straightforward to implement. Not sure I'll find time to do it soon, but this looks like a nice first patch to make if you're interested in contributing ;-).

**Comment by ism** [comment]
I am interested :-)

I have added support for 'input' type. Should i also add support for checkbox, radio, textarea and select? I am asking because, for example, in case of checkbox it's not clear what type to return - True, 'checked', None ?

**Comment by moy** [comment]
Best is to submit a minimalist and uncontroversial PR, and then we'll see.

I don't have the whole code/behavior in mind, but the goal should be to be as symmetrical as possible to the `set_*` methods in `Form`.

**Comment by dillonko** [comment]
I belive you can do something like this:

```python
b = mechanicalsoup.StatefulBrowser()
...
firstname = b.get_current_form().form.find('input', {'name': 'firstname'}).get('value')
```

**Comment by pcworld** [comment]
This appears unsolved, although there's a commit at https://github.com/ism/MechanicalSoup/commit/a71c43abaf68e22bafe3c2290193deb30a72eb62, there doesn't seem to be a pull request for it.
