### ISSUE TITLE
How to get all replies I have when I call an URL

### ISSUE THREAD

**Issue by aborruso** [MechanicalSoup/MechanicalSoup#330]
Hi,
when I call via browser this example URL "https://w3.ars.sicilia.it/icaro/default.jsp?icaDB=221&icaQuery=(open+E+data)" I have back a lot URLs and files (see below image).
I'm very interested to collect the XHR items URL. How to use MechanicalSoup to have them?

Thank you very much

![image](https://user-images.githubusercontent.com/30607/86052645-9997b980-ba57-11ea-8cba-2e0b27d3b81e.png)

**Comment by moy** [comment]
Unlike a real web browser, MechanicalSoup won't automatically download all resources linked from a page (images, CSS or JS files, ...). I'm not familiar with XHR (is it XmlHTTPRequest?), but my understanding is that it's something useful only from JavaScript. MechanicalSoup doesn't do JavaScript, so it won't help you (https://mechanicalsoup.readthedocs.io/en/stable/faq.html#form-submission-has-no-effect-or-fails).

**Comment by aborruso** [comment]
Thank you
