### ISSUE TITLE
Get stock data

### ISSUE THREAD

**Issue by lvchiyahoo** [MechanicalSoup/MechanicalSoup#346]
Hi team,

I try to get stock data at http://priceboard1.vcsc.com.vn/vcsc/intraday
we need to input the stock and date and click the buttom to get the data.

I am a newbie so I could not get it started.  I tried the below code but it does not help. 
It seems the website is using javascript (as there is no name on the input/select tag) so I need to add some tricks?

Sorry if I ask at a wrong place. Thanks a lot. 
Chi
========
import mechanicalsoup

browser = mechanicalsoup.StatefulBrowser()
browser.open("http://priceboard1.vcsc.com.vn/vcsc/intraday")

print(browser.get_url())

form = browser.select_form('div[id="container"]')
browser.get_current_form().print_summary()
browser["stockPicker"] = "ITD"
#browser["datePicker"] = "20201203"

#form.set_select("stockPicker","KDH")

form.set_input("20201113")

==========
OUTPUT:
>>> 
===== RESTART:ck.py ====
http://priceboard1.vcsc.com.vn/vcsc/intraday
<select id="stockPicker"></select>
<input class="ui-button ui-widget ui-corner-all" id="datePicker" type="text"/>
<button class="ui-button ui-widget ui-corner-all" id="showIntraday" langid="showIntraday" style="margin-left: 20px">Xem</button>
Traceback (most recent call last):

 line 11, in <module>
    browser["stockPicker"] = "ITD"
raise LinkNotFoundError("No valid element named " + name)
mechanicalsoup.utils.LinkNotFoundError: No valid element named stockPicker

**Comment by hemberger** [comment]
Thanks for your interest in MechanicalSoup!

If the page uses JavaScript and you cannot easily reconstruct the necessary form elements with [new_control](https://mechanicalsoup.readthedocs.io/en/stable/mechanicalsoup.html?highlight=new_control#mechanicalsoup.Form.new_control), then you may need to use a tool that does handle JavaScript, like Selenium. See https://mechanicalsoup.readthedocs.io/en/stable/faq.html#form-submission-has-no-effect-or-fails.

Please feel free to reopen this issue if you have any followup questions!
