### ISSUE TITLE
Use GitHub action to publish to PyPI?

### ISSUE THREAD

**Issue by hemberger** [MechanicalSoup/MechanicalSoup#352]
GitHub offers an action template to set up publishing releases to PyPI automatically. This seems like a pretty sensible improvement to our release workflow, so I was planning to set that up with a "MechanicalSoup" PyPI account. If there are any objections to this plan (@moy), please let me know!

**Comment by moy** [comment]
I didn't look at GitHub actions yet, but that sounds like a good idea, yes.

Given the pace of releases of MechanicalSoup, I suspect that we'll spend more time setting this up than we'll really save, but I like using MechanicalSoup to experiment with fun tools and automation, so, good :-).

FYI, I'll propose contributing to MechanicalSoup to my students this year again (we had no candidate last year, but a few pull-requests were merged 2 or 3 years ago). That sounds like a nice microproject for them.

**Comment by hemberger** [comment]
By the way, I used my personal PyPI account rather than a "MechanicalSoup" account, since registration requires a unique e-mail address, and we don't have one for this organization. We can update the repository secrets at any time should ownership change or if we acquire an appropriate e-mail address later.
