### ISSUE TITLE
Incorrect encoding detected when the page does not set its encoding through a meta tag

### ISSUE THREAD

**Issue by LVerneyPEReN** [MechanicalSoup/MechanicalSoup#354]
Hi,

I noticed issues of incorrect encoding detected by BeautifulSoup for a webpage which sets its encoding in the HTTP headers (requests get the right encoding) but does not specify it at the HTML level through a `<meta>` tag. In my case, the page was UTF-8 encoded but BeautifulSoup4 detects it as "Windows-1252".

I noticed encoding from obtained from requests is not passed along to BeautifulSoup in MechanicalSoup: https://github.com/MechanicalSoup/MechanicalSoup/blob/c8f39e673df70c43fcea623d8c2a649fdca95f91/mechanicalsoup/browser.py#L65-L69.

I think the issue could be fixed by using something along:

```python
response.soup = bs4.BeautifulSoup(response.content, encoding=response.encoding, **soup_config)
```

but there might be additional side effects which I do not foresee.

Is there a reason for not doing so?

Thanks!
Best,

**Comment by moy** [comment]
Hi,

I don't think there's a reason for not doing what you suggest. We haven't worked much on encoding in MechanicalSoup, I guess that's the explanation.

If we go for this, obviously this will also need a test.

Do you want to work on a patch?

Regards,

**Comment by hemberger** [comment]
Here's an interesting suggestion from https://stackoverflow.com/a/45643551, i.e.
```python
from bs4 import BeautifulSoup
from bs4.dammit import EncodingDetector
resp = requests.get(url)
http_encoding = resp.encoding if 'charset' in resp.headers.get('content-type', '').lower() else None
html_encoding = EncodingDetector.find_declared_encoding(resp.content, is_html=True)
encoding = html_encoding or http_encoding
soup = BeautifulSoup(resp.content, 'lxml', from_encoding=encoding)
```
I think something like this might be needed to account for the case where the encoding is in the HTML, but not in the headers.

**Comment by LVerneyPEReN** [comment]
@hemberger Indeed! I'm wondering if there could be cases where HTTP request encoding (as returned by HTTP headers / `requests.encoding`) differ from the HTML encoding (as defined in the `<meta>` tag) though?

**Comment by hemberger** [comment]
I imagine anything is possible out in the wild. I'm not sure that it will be possible to correctly handle every kind of misconfiguration, though. Therefore, would we want to provide an interface for enforcing a specific encoding?
