### ISSUE TITLE
Migrate from TravisCI to GitHub Actions?

### ISSUE THREAD

**Issue by hemberger** [MechanicalSoup/MechanicalSoup#357]
As of Nov 2020, TravisCI has given open source projects on their "Free" plan 10k build credits. These are non-renewable, and we have already used 2630 of 10000 credits. Each time we trigger the tests, we use about 50 credits, so we may want to preempt the eventual message that I recently got for other projects:
> Builds have been temporarily disabled for private and public repositories due to a negative credit balance.

According to the [TravisCI FAQ](https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source), we can e-mail them to request an additional one-time OSS credit allotment, and _potentially_ get a monthly allotment once that is used up. We can try to do this, but I've heard stories about unsatisfying interactions with their support team.

Ultimately, it may be less effort to simply switch to GitHub Actions.

**Comment by hemberger** [comment]
Update as of 2021-04-21:
> You have used 4430 of 10000 credits

**Comment by maximino-dev** [comment]
I recently learned how to use github actions, and created a file which is very similar to the travis.yml file.
Github actions seems very easy to use and can be used in an unlimited way.

Here's what the file looks like :
`
name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "pypy3"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies for pypy3
      if: ${{ matrix.python-version == 'pypy3' }}
      run: |
        sudo apt-get install python-dev libxml2-dev libxslt-dev libz-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r tests/requirements.txt
    - name: Lint with flake8
      run: |
        flake8 --version
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then pytest -o 'flake8-ignore=*.py ALL'; fi
        if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pytest; fi
`

I added an if condition to install dependencies for the pypy3 version, otherwise I get an error.

This file is a yaml file too and needs to be added in the _.github/workflows/_ folder. Then, every push or pull_request will run those commands. 

I saw that it's possible to write codecov commands into this file too but it needs the codecov project's token.

**Comment by moy** [comment]
Can you submit this file as a pull-request?

Why limit this to the master branch? (if we special-case a branch name, we should also include `main` to take into account  #383)

This `pypy3` special-case deserves at least a comment in the Yaml file. I'm actually surprised that the `actions/setup-python@v2` doesn't just do the right thing for us.

**Comment by hemberger** [comment]
Thanks for looking into this! I agree that a PR would be great once the details are ironed out.

A couple other points:
* The Codecov authorization should be inherited naturally once it's running in the MechanicalSoup org. No token is necessary because it's a public project.
* I'd be surprised if we needed to alter the environment for pypy3. Could you link to an Actions log that shows the error?
* flake8 is already run as part of pytest, so I don't think we need to run it manually.

**Comment by hemberger** [comment]
As a followup about `pypy3`, I see two error messages in your [Actions log](https://github.com/maximino-dev/MechanicalSoup/runs/5098337850?check_suite_focus=true):

> Error: Please make sure the libxml2 and libxslt development packages are installed.

> Using legacy 'setup.py install' for lxml, since package 'wheel' is not installed.

However, I think these are a bit misleading, because the underlying issue seems to be that the most recent version of `lxml` (4.7.1) only provides wheels for `pypy-3.7` and `pypy-3.8` (https://pypi.org/project/lxml/4.7.1/#files), but `pypy3` in the GitHub Action defaults to `pypy-3.6`. Let's try explicitly specifying `pypy-3.8` without any additional installations and see if that solves the problem.

Thanks again!

**Comment by maximino-dev** [comment]
I corrected all the remaining details in the PR #384.
Now, push and pull-requests are triggered, no matter the branch, and specifying pypy-3.8 solved the problem correctly, thank you for those details.
