### ISSUE TITLE
Nested forms

### ISSUE THREAD

**Issue by arnaudde** [MechanicalSoup/MechanicalSoup#36]

**Comment by eoghanmurray** [comment]
Is the problem in trying to submit the parent form or the child form?
This sounds like bad/malformed HTML on a page and maybe something that could be dealt with by extracting the nested form and placing it alongside the parent form before submitting: https://www.crummy.com/software/BeautifulSoup/bs4/doc/#extract

**Comment by hemberger** [comment]
Nested forms do not appear to be valid html5. See, for example, https://stackoverflow.com/a/379622. I recommend closing this issue.

**Comment by moy** [comment]
I don't think anything is going to happen to this issue unless we have a valid use-case. I'm closing it for now, please re-open with more details on why this could be interesting if needed.
