### ISSUE TITLE
Installs in 3.8

### ISSUE THREAD

**Issue by wkeuffel** [MechanicalSoup/MechanicalSoup#372]
while running python3.9 on pop os, installed mechanical soup with

python3 -m pip install MechanicalSoup

which installed the package in

./.local/lib/python3.8/site-packages

unable to import mechanicalsoup

Manually moved from python3.8 to python3,9

which solved the import problem

**Comment by moy** [comment]
I guess `python3.9 -m pip install MechanicalSoup` would have installed the package in the right directory. `pip` installs in the directory corresponding to the Python version used when running pip itself.
