### ISSUE TITLE
Fetching completed view ( HTML ) - dynamic web pages 

### ISSUE THREAD

**Issue by VemalapalliVenkatesh** [MechanicalSoup/MechanicalSoup#377]
I am expecting to get complete web page ( Dynamic content as well ) . But Mechanical Soup unable to get complete web page HTML . 
It is giving only the typical page source ( view page source ) . 
If the web page is having static content library working fine , if the page contains JavaScript it is failed to get complete HTML . 

Configuration used  : 
browser = mechanicalsoup.StatefulBrowser(
    soup_config={'features': 'lxml'},
    raise_on_404=True,
    user_agent='MechanicalSoup',
)

calling -     browser.open("https://www.google.com/")

**Comment by moy** [comment]
This is expected and documented: MechanicalSoup doesn't do JavaScript, you need to use a more powerful (and heavier) library if you need JS support.
