### ISSUE TITLE
How to persistent cookies for browser like real browser?

### ISSUE THREAD

**Issue by lededev** [MechanicalSoup/MechanicalSoup#379]
How to do this, every time, like real browser dose.
I'm stuck in the second and third steps, after open, I can get cookies from session, but before open, I do not know how to set cookies and let browser use my cookies.

1. load cookies from file
2. open browser with cookies above
3. open url with cookies and update cookies
4. follow_links with cookies and update cookies
5. form submit with cookies and update cookies
6. close browser
7. save updated cookies to file

**Comment by moy** [comment]
Cookies are naturally "persistent" in MechanicalSoup in the sense "kept from one request to another". They are not persistent from one MechanicalSoup session to another (i.e. if you terminate your Python program and restart it, cookies are lost).

Saving cookies in a file is possible, it has been discussed here: https://github.com/MechanicalSoup/MechanicalSoup/issues/37

No time to actually try this, but probably we should add a mention of it in the doc (no time either for that ;-) ).

**Comment by lededev** [comment]
Save is not the problem, but the initial load is.
I tried many way, but failed to set cookies before open URL.

`requests.utils.add_dict_to_cookiejar(browser.session.cookies, cookies)`
failed
`browser = mechanicalsoup.StatefulBrowser(url,cookies=cookies)`
failed
replace mechanicalsoup browser requests object with a set cookiejar requests object on init failed.

**Comment by moy** [comment]
You can initialize a requests session before creating the browser, and pass it to the constructor of `StatefulBrowser` (parameter `session`).

**Comment by lededev** [comment]
Thank you, this is a right way.
```
s = requests.Session()
requests.utils.add_dict_to_cookiejar(s.cookies, {'key1': 'val1'})
browser = mechanicalsoup.StatefulBrowser(session=s)
r = browser.open(url)
```
and browser.open return r.ok

**Comment by lededev** [comment]
Well, this code can run, but cookies not really sent to web server, `requests.get(url, cookies=my_custom_cookies)` do real job, `requests.utils.add_dict_to_cookiejar(s.cookies, {'key1': 'val1'})` cookies not be used when browser.open()

**Comment by moy** [comment]
No need to write a new server, httpbin is there. It does work, indeed, see 72783b827b176bec8a3f9672a5222ce835b72a82.
