### ISSUE TITLE
Cannot install MechanicalSoup on Kodi 19.3

### ISSUE THREAD

**Issue by dgiglio** [MechanicalSoup/MechanicalSoup#381]
I get this error when trying to resolve the dipendencies for AmazonVOB
`ERROR <general>: Add-on 'script.module.mechanicalsoup' is not compatible with Kodi`

**Comment by hemberger** [comment]
Thanks for your bug report. It looks like people have found a resolution to this issue within xbmc: https://github.com/Sandmann79/xbmc/issues/592.
