### ISSUE TITLE
Submit form with no button

### ISSUE THREAD

**Issue by alexreg** [MechanicalSoup/MechanicalSoup#403]
Some web pages use JavaScript postbacks to submit forms. This means that a submitted form has nothing to do with which button is pressed. In fact, including form data for the "pressed" button can mess things up in such a case.

Accordingly, it would be great to have a way of specifying that *no* button "press" should be simulated when calling `submit_selected`. Right now, `btnName = None` means that the first "submit" button is auto-selected — but there is no way to specify that *no* submit button press should be simulated. Perhaps another (boolean) parameter could be used for this? The `Form.choose_submit` method would also need to be enhanced accordingly.

**Comment by hemberger** [comment]
Sorry for the excessively slow reply to this issue! I see your point about having no way to specify that _no_ submit button should be simulated. If this is still relevant to you, we can certainly consider an enhancement here. Maybe the simplest thing would be to skip selecting a submit if `btnName=False` (to avoid needing to handle all the combinations of `btnName` with some additional boolean flag):

```python
if btnName is not False:
    self.form.choose_submit(btnName)
```
You can also use `Browser.submit` directly, but obviously that doesn't help if you want to use StatefulBrowser features with this.

**Comment by alexreg** [comment]
@hemberger Thanks for getting back to me. Yes, I'd certainly still be keen to see this feature implemented. The way you've suggested seems like a very simple change, and would no doubt work for me.

**Comment by moy** [comment]
If you have time to work on it, pull-requests are welcome (the code itself should be straightforward, but there should be a test which may require a bit more time to write). We may get time to implement it ourselves, but at least I have very limited time for MechanicalSoup :-(.
