### ISSUE TITLE
Page redirect not being followed

### ISSUE THREAD

**Issue by alper** [MechanicalSoup/MechanicalSoup#405]
I have a page that's redirecting, but I'm not sure why MechanicalSoup does not follow it. I got that part to work in mechanize (based on its verbose logging) but then it hung.

I'm also not sure how I can display full header and body from the server for each request/response in MechanicalSoup. `set_verbose` and `logging` don't display too much information. If I could do that, I could see the redirect there and then follow that link manually for now.

**Comment by hemberger** [comment]
Hi, thanks for your question! MechanicalSoup uses the `requests` module under the hood, which follows redirects by default (see https://requests.readthedocs.io/en/latest/api/). All of our methods should give you access to the response object, so you can look at `response.headers` or `response.content` for the headers or content respectively. You also have direct access to the request that generated the response with `response.request`.

**Comment by hemberger** [comment]
I will close this issue now, but if you have any further questions, please feel free to reopen it.
