### ISSUE TITLE
Rate Limiting

### ISSUE THREAD

**Issue by cerquide** [MechanicalSoup/MechanicalSoup#414]
I am trying to use MechanicalSoup to crawl a site which has rate limits.  Is there any way to instruct MechanicalSoup to respect these? 

I am planning to add this feature by using the [ratelimiter](https://pypi.org/project/ratelimiter/) package. Do you think it makes sense to send a PR with this functionality once I have done it?

**Comment by hemberger** [comment]
Hi, thanks for your interest in MechanicalSoup! Please forgive my ignorance, but since MechanicalSoup only makes a single HTTP request in any given call, would it make sense for something like ratelimiter to be used by the caller rather than MechanicalSoup itself? I'm more hesitant than usual to introduce it as a dependency as it hasn't been maintained for about 5 years.

**Comment by cerquide** [comment]
Hi Dan, 

Your are absolutely right, this is in fact what I did while waiting for your reply. In my opinion it makes no sense to incorporate rate limiting into MechanicalSoup, because it can be incorporated easily by the caller. I leave the code that I have used as an example next.

```
import mechanicalsoup as ms
from ratelimiter import RateLimiter

# This is the rate limited browser class
class RLBrowser(ms.StatefulBrowser):
    def __init__(self, rl: RateLimiter, *args, **kwargs):
        ms.StatefulBrowser.__init__(self, *args, **kwargs)
        self.rl = rl

    def get(self, *args, **kwargs):
        with self.rl:
            return ms.StatefulBrowser.get(self, *args, **kwargs)

# Callback that is called every time that a request is stopped due to rate limit
def limited(until):
    duration = int(round(until - time.time()))
    logging.info('Rate limited, sleeping for {:d} seconds'.format(duration))

rate_limiter = RateLimiter(max_calls=3, period=1, callback=limited)
browser = RLBrowser(rate_limiter)

# An from here on, regular use of MechanicalSoup
```
