### ISSUE TITLE
form action without schema'ed ACTION fails with MissingSchema

### ISSUE THREAD

**Issue by chadmiller** [MechanicalSoup/MechanicalSoup#49]
Used `requests` (and mechanicalsoup) to .get() a web page that has a form on it. The form tag looks like

`<form action="/submit_uri" method="post">`

I filled a part of the form, and then .submit()ed the form.

```
  File mechanicalsoup/browser.py", line 114, in submit
    request = self._prepare_request(form, url, **kwargs)
  File "mechanicalsoup/browser.py", line 109, in _prepare_request
    return self.session.prepare_request(request)
  File "requests/sessions.py", line 394, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "requests/models.py", line 294, in prepare
    self.prepare_url(url, params)
  File "requests/models.py", line 354, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/submit_uri': No schema supplied. Perhaps you meant http:///submit_uri?
```

**Comment by chadmiller** [comment]
Probably, should depend on 

https://pypi.python.org/pypi/rfc3987

and use its `parse(first_url)` and incrementally `resolve(discovered_web_page_url, current_url)`

**Comment by lchski** [comment]
Just had this problem. By default, the library doesn’t handle relative URLs. The fix is is mentioned in #10: you need to pass the current page URL to the `.submit()` method, which parses it and creates an absolute URL.

**Comment by moy** [comment]
I believe this is fixed in recent versions of MechanicalSoup (e.g. 2424deabd9fe2a58d8f11829c695fdd2e5a99d89). If so, please close the bug. If not, then can you please submit a testcase ?

Thanks,

**Comment by moy** [comment]
No answer so I'll close this, but feel free to re-open if you have more info to provide..
