### ISSUE TITLE
Submit a multipart encripted form

### ISSUE THREAD

**Issue by ericbrandwein** [MechanicalSoup/MechanicalSoup#90]
This library doesn't seem to support forms with `enctype='multipart/form-data'`. Are there any plans for supporting these?

**Comment by hemberger** [comment]
I tried modifying one of the tests that use a mock browser to include `enctype="multipart/form-data"` and the test still passed. Can you please provide more detail about the error you are seeing (and, if possible, the website or form that you are submitting)? Thanks!

**Comment by moy** [comment]
@ericbrandwein : can you send us more details about your issue? Otherwise, let's close the bug.

**Comment by hemberger** [comment]
I tested that MechanicalSoup is correctly handling `enctype='multipart/form-data'` on [this site](http://www.csm-testcenter.org/test?do=show&subdo=common&test=file_upload) while testing file upload. It has the following form:

```html
<h1>File upload via POST (HTTP)</h1>
<form action="http://www.csm-testcenter.org/test" enctype="multipart/form-data" method="POST">
    <input type="hidden" name="do" value="test">
    <input type="hidden" name="subdo" value="file_upload">

    <table>
        <tbody>
            <tr>
                <td align="right" valign="top" nowrap="">File to upload</td>
                <td align="left" valign="top"><input type="file" name="file_upload" size="45"></td>
            </tr>

            <tr>
                <td align="right" valign="top" nowrap="">Send back received data</td>
                <td align="left" valign="top"><input type="checkbox" name="info"></td>
            </tr>

            <tr>
                <td align="right" valign="top" nowrap=""></td>
                <td align="left" valign="top"><input id="button" type="submit" name="http_submit" value="Start HTTP upload"></td>
            </tr>
        </tbody>
    </table>
</form>
```

I was able to successfully submit the form using this script:
```python
import mechanicalsoup as ms
br = ms.StatefulBrowser(raise_on_404=True)
br.open('http://www.csm-testcenter.org/test?do=show&subdo=common&test=file_upload')
form = br.select_form()
form['file_upload'] = '/path/to/some/file'
br.submit_selected()
```

If you are still having issues, please don't hesitate to contact us again. We're happy to help if you can provide more details!
