### ISSUE TITLE
Enable codecov.io webhooks

### ISSUE THREAD

**Issue by hemberger** [MechanicalSoup/MechanicalSoup#99]
Currently, codecov.io can only add comments to PR's. However, there's a lot more it can do when integrated directly into GitHub using the [official app](https://github.com/apps/codecov). Can this be enabled in the repository? I'm not sure if it requires an admin or the repository owner.

An example of the additional context elements enabled by this app:
![image](https://user-images.githubusercontent.com/846186/31074361-208f2a16-a725-11e7-91d0-8df37e74c9b9.png)
(The screenshot is from my fork where I have the app installed.)

**Comment by moy** [comment]
I'm all for it, but AFAIK, only @hickford can do this. At least, I tried installing it and it showed only my fork of MechanicalSoup, not the official one.

So, @hickford , can you:

* Open https://codecov.io/gh
* Log-in with your GitHub credential
* Then you should get an invitation to install codecov.io to your repo, you're a few clicks away.

Thanks,

**Comment by hickford** [comment]
If it helps, I've transferred the repo to its own organisation https://github.com/MechanicalSoup/MechanicalSoup

**Comment by hemberger** [comment]
Thanks! This should allow us to set up the Codecov app. I'll discuss with @moy.

**Comment by moy** [comment]
Thanks for the move to an organization. However, AFAICT I still don't have permission to enable codecov.io. I'm "outside collaborator" in the MechanicalSoup org, and I think I need to be "owner" to do this.

**Comment by moy** [comment]
OK, not sure whether I fixed something on my side or whether @hickford did, but I'm now a co-owner of the org. I *think* I enabled codecov.io properly, but I'm not 100% sure I did it right. Anyway, @hemberger, feel free to fix any mis-configuration I may have done. In the meantime, let's close this.
